packages/api/prisma/migrations/20211102101051_/migration.sql, packages/api/prisma/schema.prisma, packages/api/src/controllers/auth/User.ts, packages/api/src/lib/auth.ts, packages/client/locales/en/account.json, packages/client/src/components/account/AppearanceTab.tsx, packages/client/src/components/account/ChangePasswordArea.tsx, packages/client/src/components/dispatch/ActiveDeputies.tsx, packages/client/src/components/dispatch/ActiveOfficers.tsx, packages/client/src/pages/account.tsx, packages/client/src/types/prisma.ts
=> :tada: Appearance tab & Status view mode

packages/client/src/components/Dropdown.tsx, packages/client/src/components/leo/ActiveCalls.tsx
=> :tada: feat: highlight currently assigned to call

packages/api/src/controllers/leo/SearchController.ts, packages/client/src/components/leo/modals/VehicleSearch/TruckLogsTable.tsx, packages/client/src/components/leo/modals/VehicleSearchModal.tsx, packages/client/src/pages/dispatch/index.tsx, packages/client/src/pages/officer/index.tsx, packages/client/src/types/prisma.ts
=> 🎉 feat: show truck-logs on PlateSearch

packages/api/src/controllers/dispatch/Calls911Controller.ts, packages/client/locales/en/calls.json, packages/client/src/components/leo/ActiveCalls.tsx
=> :tada: feat: able to unassign from call

packages/api/src/controllers/auth/User.ts, packages/api/src/controllers/dispatch/StatusController.ts, packages/api/src/lib/leo/handleStartEndOfficerLog.ts
=> :tada: feat: set units off-duty on logout

packages/api/prisma/migrations/20220217150844_/migration.sql, packages/api/prisma/schema.prisma, packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts, packages/client/locales/en/calls.json, packages/client/src/components/leo/ActiveCalls.tsx, packages/client/src/components/modals/Manage911CallModal.tsx, packages/schemas/src/dispatch/911-calls.ts, packages/types/src/index.ts
=> :tada: feat: allow attaching situation codes to calls

packages/api/package.json, packages/api/prisma/migrations/20220220123028_/migration.sql, packages/api/prisma/schema.prisma, packages/api/src/controllers/dispatch/StatusController.ts, packages/api/src/lib/leo/handleStartEndOfficerLog.ts, packages/api/src/migrations/pairedSymbolToTemplate.ts, packages/client/package.json, packages/client/src/components/dispatch/ActiveOfficers.tsx, packages/client/src/hooks/useGenerateCallsign.ts, packages/utils/README.md, packages/utils/package.json, packages/utils/src/callsign.ts, packages/utils/src/index.ts, packages/utils/tsconfig.json, scripts/bump-version.mjs, yarn.lock
=> 🔨 chore: add `@snailycad/utils` package

packages/api/prisma/migrations/20220223131255_/migration.sql, packages/api/prisma/schema.prisma, packages/api/src/controllers/dispatch/DispatchController.ts, packages/api/src/controllers/leo/incidents/IncidentController.ts, packages/api/src/controllers/leo/incidents/IncidentEventsController.ts, packages/api/src/lib/officer.ts, packages/api/src/services/SocketService.ts, packages/client/locales/en/leo.json, packages/client/src/components/dispatch/ActiveIncidents.tsx, packages/client/src/components/dispatch/ActiveOfficers.tsx, packages/client/src/components/leo/incidents/IncidentEventsArea.tsx, packages/client/src/components/leo/incidents/ManageIncidentModal.tsx, packages/client/src/components/modals/events/EventItem.tsx, packages/client/src/components/modals/events/UpdateEventForm.tsx, packages/client/src/pages/officer/incidents.tsx, packages/config/src/socket-events.ts, packages/types/src/index.ts
=> :tada: feat: active incidents events

packages/api/prisma/migrations/20220301110033_call_via_dispatch/migration.sql, packages/api/prisma/schema.prisma, packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts, packages/client/src/components/leo/ActiveCalls.tsx, packages/types/src/index.ts
=> :tada: feat: inform if call is created via dispatch

packages/api/src/lib/records/penal-code.ts, packages/client/src/components/admin/values/penal-codes/ManagePenalCode.tsx, packages/schemas/src/admin/values/import.ts
⚠️ needs further testing. **docs must be updated**
=> :tada: feat: allow warning and warning not applicable at same time

packages/client/src/components/admin/values/import/OptionsDropdown.tsx, packages/client/src/pages/admin/values/[path].tsx, packages/client/src/pages/admin/values/penal-code.tsx
=> :tada: feat: allow export of admin values

production.docker-compose.yml
- On Docker Installations, the cad will now auto-restart when the machine crashes / reboots.
=> Restart CAD on machine boot (Docker)

packages/client/package.json, packages/client/src/components/dispatch/active-units/UnitRadioChannelModal.tsx, packages/client/src/components/nav/dropdowns/CitizenDropdown.tsx, packages/client/src/components/nav/dropdowns/DispatchDropdown.tsx, packages/client/src/components/nav/dropdowns/EmsFdDropdown.tsx, packages/client/src/components/nav/dropdowns/OfficerDropdown.tsx, yarn.lock
This should stop the spamming requests to `/socket.io?...` to the API. This should also save bandwidth.
=> :hammer: fix: update @casper124578/use-socket.io

packages/api/prisma/migrations/20220403064022_/migration.sql, packages/api/prisma/schema.prisma, packages/api/src/controllers/admin/manage/cad-settings/CadSettings.ts, packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts, packages/api/src/controllers/leo/incidents/IncidentController.ts, packages/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx, packages/schemas/src/admin/index.ts, packages/types/src/index.ts
=> :tada: feat: restrictions for calls (optional)

packages/api/prisma/migrations/20220413055643_/migration.sql, packages/api/prisma/schema.prisma, packages/api/src/controllers/admin/manage/cad-settings/CadSettings.ts, packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts, packages/api/src/controllers/dispatch/DispatchController.ts, packages/api/src/lib/leo/utils.ts, packages/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx, packages/schemas/src/admin/index.ts, packages/types/src/index.ts
=> 🎉 feat: end active calls & incidents after timeout (optional)

packages/api/src/controllers/leo/incidents/IncidentController.ts, packages/client/locales/en/leo.json, packages/client/src/components/dispatch/ActiveDeputies.tsx, packages/client/src/components/dispatch/ActiveIncidents.tsx, packages/client/src/components/dispatch/active-incidents/InvolvedUnitsColumn.tsx, packages/client/src/components/dispatch/active-units/officers/OfficerColumn.tsx, packages/client/src/components/leo/ActiveCalls.tsx, packages/client/src/components/leo/active-calls/AssignedUnitsColumn.tsx, packages/client/src/state/dispatchState.ts, packages/client/src/types/DndActions.ts
=> :tada: feat: drag-drop for active incident units involved

packages/client/locales/en/leo.json, packages/client/src/components/shared/StatusesArea.tsx, packages/client/src/hooks/shared/useUnitLastStatusChange.tsx, packages/client/src/pages/ems-fd/index.tsx, packages/client/src/pages/officer/index.tsx, packages/types/src/index.ts
=> 🎉 feat: add simple warning if unit is inactive

packages/api/prisma/migrations/20220715065900_/migration.sql, packages/api/prisma/schema.prisma, packages/api/src/controllers/record/RecordsController.ts, packages/api/src/middlewares/ActiveOfficer.ts, packages/client/src/components/leo/citizen-logs/ArrestReportsTab.tsx, packages/client/src/components/leo/modals/NameSearchModal/tabs/RecordsTab.tsx, packages/client/src/pages/officer/jail.tsx, packages/types/src/api/admin.ts, packages/types/src/index.ts
=> :tada: feat: ability to create records via 'snaily-cad-api-token'

packages/api/src/controllers/admin/manage/cad-settings/CADImagesController.ts, packages/api/src/controllers/admin/manage/cad-settings/CadSettings.ts, packages/api/src/controllers/admin/manage/cad-settings/discord/DiscordSettingsController.ts, packages/api/src/controllers/admin/manage/cad-settings/discord/DiscordWebhooksController.ts, packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts, packages/api/src/controllers/leo/incidents/IncidentController.ts, packages/api/src/middlewares/auth/getUser.ts, packages/api/src/middlewares/auth/utils.ts, packages/client/src/components/admin/Sidebar.tsx, packages/client/src/components/admin/manage/users/ManagePermissionsModal.tsx, packages/client/src/context/AuthContext.tsx, packages/config/package.json, packages/config/src/routes.ts, packages/permissions/src/defaults/admin.ts, packages/permissions/src/permissions.ts, yarn.lock
=> :tada: feat: able to grant users manage cad-settings permissions

packages/client/locales/fr_FRA/leo.json
`rev/240722: update leo.json (fr_FRA)`
=> 🛠️ Update leo.json (fr_FRA)

packages/client/locales/fr_FRA/common.json
=> :hammer_and_wrench: Update common.json (fr_FRA)

packages/client/locales/de_DE/citizen.json, packages/client/locales/fr_FRA/citizen.json
=> :globe_with_meridians: Add 'Additional Info' in FRA and DEU

apps/api/src/controllers/dispatch/StatusController.ts, apps/api/src/lib/ems-fd.ts, apps/api/src/lib/leo/activeOfficer.ts, apps/client/src/components/active-bolos/BoloItem.tsx, apps/client/src/components/ems-fd/ModalButtons.tsx, apps/client/src/components/leo/ModalButtons.tsx, apps/client/src/pages/ems-fd/index.tsx, apps/client/src/pages/officer/index.tsx
=> :tada: feat: allow admins to use modal buttons (ref #1133)

apps/client/locales/en/leo.json
Update the "en" locales for leo.json to fix capitalization.
=> (Locales)  Update leo.json

apps/api/prisma/migrations/20221207131235_active_dispatchers_activity_timeout/migration.sql, apps/api/prisma/schema.prisma, apps/api/src/controllers/admin/manage/cad-settings/CadSettings.ts, apps/api/src/controllers/dispatch/DispatchController.ts, apps/api/src/lib/leo/utils.ts, apps/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx, apps/client/src/components/admin/manage/cad-settings/misc-features/InactivityTimeoutSection.tsx, packages/schemas/src/admin/index.ts
=> :tada: feat: add inactivity timeout for dispatchers

Dockerfile
**Docker installation did not work properly**
The start process was blocking because the workspace was not being retrieved from the CMD context of the generic Dockerfile, to which adding in the environment variables solved the problem 
This PR does not change the other installation methods and has no breaking change :)
=> 🔨 fix : BUILD_CONTEXT available from CMD context by adding it as env

apps/api/src/controllers/dispatch/911-calls/Calls911Controller.ts, apps/api/src/controllers/leo/incidents/IncidentController.ts, apps/api/src/lib/calls/getNextActiveCall.ts, apps/api/src/lib/incidents/get-next-incident-id.ts
=> :tada: feat: support `force` option for assigning to call/incident

apps/api/src/controllers/dispatch/dispatch-controller.ts, apps/client/src/components/dispatch/ModalButtons.tsx, apps/client/src/components/shared/UtilityPanel.tsx, apps/client/src/hooks/realtime/useActiveDispatchers.ts, apps/client/src/pages/dispatch/index.tsx, apps/client/src/state/dispatch/active-dispatcher-state.ts, apps/client/src/state/dispatch/dispatch-state.ts, packages/types/src/api/dispatch.ts
Only returns the `activeDispatchersCount` instead of all active dispatchers array. For the user active dispatcher, this now returns `userActiveDispatcher`
=> chore: improve loading of active dispatchers

apps/api/src/controllers/leo/my-officers/MyOfficersController.ts, apps/client/src/components/dispatch/modals/CallTowModal.tsx, apps/client/src/components/leo/modals/select-officer-modal.tsx, apps/client/src/hooks/ems-fd/use-get-user-deputies.ts, apps/client/src/hooks/leo/use-get-user-officers.ts, apps/client/src/pages/ems-fd/index.tsx, apps/client/src/pages/ems-fd/my-deputy-logs.tsx, apps/client/src/pages/officer/index.tsx, apps/client/src/pages/officer/my-officer-logs.tsx, apps/client/src/state/leo-state.ts, packages/types/src/api/leo.ts
- only load user officers/deputies when needed
- Don't load user officers/deputies on SSR because they're not needed until a modal is opened.
=> chore: only load my officers/deputies when needed

apps/api/src/controllers/admin/AdminController.ts, apps/api/src/controllers/admin/values/values-controller.ts, apps/client/locales/en/values.json, apps/client/src/pages/admin/values/[path].tsx, apps/client/src/pages/admin/values/penal-code/[groupId].tsx
=> chore: cache /values/<path>

apps/client/locales/ru/admin.json
Added missing translation to `admin.json`
✅  `.json` files are formatted: `yarn format`
✅  Translations are correct
In this PR I've added the missing translation to the admin.json of the RU locale
=> 🌐  add missing translation

apps/api/prisma/migrations/20230920140633_status_value_text_color/migration.sql, apps/api/prisma/schema.prisma, apps/api/src/controllers/admin/values/import-values-controller.ts, apps/client/locales/en/values.json, apps/client/src/components/admin/values/ManageValueModal.tsx, apps/client/src/components/admin/values/manage-modal/status-value-fields.tsx, apps/client/src/components/dispatch/active-units/deputies/active-deputies.tsx, apps/client/src/components/dispatch/active-units/officers/active-officers.tsx, packages/schemas/src/admin/values/import.ts
=> feat: text color for 10-codes

package.json
This can be used to streamline the process of a full-start by copying the `.env` file, building and starting in processes like pm2, SnailyCAD Manager, and more where it might not be possible to run each command separately or together with the `&&` operator in a standalone terminal.
Feel free to review and share thoughts!
=> 🧹 Add full-start script

package.json
to avoid package.json custom port issues
=> add git stash to full-start

apps/api/src/controllers/business/BusinessController.ts, apps/api/src/controllers/citizen/vehicles-controller.ts, apps/client/locales/en/citizen.json, apps/client/src/components/citizen/vehicles/modals/transfer-vehicle-modal.tsx, packages/schemas/src/citizen.ts
=> feat: able to transfer vehicle to business

apps/api/prisma/migrations/20231110181854_extra_fields_emergency_vehicle/migration.sql, apps/api/prisma/schema.prisma, apps/api/src/controllers/admin/values/import-values-controller.ts, packages/schemas/src/admin/values/import.ts
=> feat: extraFields for emergency vehicle value

apps/client/next.config.mjs, apps/client/tests/utils.test.ts
=> 🧹 chore: remove deprecated "images.domains"

apps/api/src/controllers/bleeter/bleeter-controller.ts
closes: [#1928](https://github.com/SnailyCAD/snaily-cadv4/issues/1928) 
Fixed it so the logic allows you to delete your own bleets w/o admin perms
=> 🛠️ | Changed permissions for users to be able to delete their own bleets w/o administrator permissions

turbo.json
With newer versions of turbo, there is a new UI for each task that is running. There are 2 reasons I see as a good fit to revert the UI.
- It can be difficult to navigate for users who don't have much experience navigating and using the command line
- The logs will not show properly in the manager, and will make diagnosing issues difficult for those who use the manager
Casper, please let me know your thoughts, and feel free to merge if you agree.
Thanks 🙂!
=> 🧹 chore: revert turbo ui
