SnailyCAD/snaily-cadv4

packages/client/src/components/Button.tsx
packages/client/src/components/admin/manage/BanArea.tsx
packages/client/src/components/admin/manage/DangerZone.tsx
packages/client/src/components/business/manage/EmployeesTab.tsx
packages/client/src/components/business/manage/PendingEmployeesTab.tsx
packages/client/src/components/citizen/LicensesCard.tsx
packages/client/src/components/citizen/MedicalRecords.tsx
packages/client/src/components/citizen/VehiclesCard.tsx
packages/client/src/components/citizen/WeaponsCard.tsx
packages/client/src/components/leo/modals/NameSearchModal/RecordsArea.tsx
packages/client/src/context/AuthContext.tsx
packages/client/src/pages/admin/manage/citizens.tsx
packages/client/src/pages/admin/manage/units/[id].tsx
packages/client/src/pages/admin/manage/units/index.tsx
packages/client/src/pages/admin/manage/users/[id].tsx
packages/client/src/pages/admin/manage/users/index.tsx
packages/client/src/pages/auth/login.tsx
packages/client/src/pages/auth/register.tsx
packages/client/src/pages/auth/temp-password.tsx
packages/client/src/pages/business/[id]/[employeeId]/index.tsx
packages/client/src/pages/business/[id]/[employeeId]/manage.tsx
packages/client/src/pages/citizen/[id]/edit.tsx
packages/client/src/pages/citizen/[id]/index.tsx
packages/client/src/pages/citizen/create.tsx
packages/client/src/pages/citizen/index.tsx
packages/client/src/pages/taxi.tsx
packages/client/src/pages/truck-logs.tsx

:tada: greater support for dark-mode

---

packages/api/prisma/migrations/20211105062536_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/Values.ts
packages/api/src/controllers/dispatch/Calls911Controller.ts
packages/api/src/controllers/dispatch/StatusController.ts
packages/api/src/controllers/ems-fd/EmsFdController.ts
packages/api/src/controllers/leo/LeoController.ts
packages/client/src/components/admin/values/ManageValueModal.tsx
packages/client/src/components/context-menu/ContextMenu.tsx
packages/client/src/components/dispatch/modals/ManageUnit.tsx
packages/client/src/components/ems-fd/StatusesArea.tsx
packages/client/src/components/ems-fd/modals/SelectDeputy.tsx
packages/client/src/components/form/FormField.tsx
packages/client/src/components/form/Select.tsx
packages/client/src/components/leo/ActiveCalls.tsx
packages/client/src/components/leo/StatusesArea.tsx
packages/client/src/components/leo/modals/SelectOfficerModal.tsx
packages/client/src/components/modals/911Call/EventsArea.tsx
packages/client/src/components/modals/Manage911CallModal.tsx
packages/client/src/types/prisma.ts
packages/config/src/routes.ts

:tada: quick events 

---

packages/api/prisma/migrations/20211108153517_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/citizen/CitizenController.ts
packages/api/src/controllers/citizen/LicenseController.ts
packages/client/src/components/citizen/LicensesCard.tsx
packages/client/src/components/citizen/modals/ManageLicensesModal.tsx
packages/client/src/pages/citizen/create.tsx
packages/client/src/types/prisma.ts

:tada: fix #134

---

packages/api/prisma/migrations/20211109183706_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/citizen/CitizenController.ts

:bug: fix #141

---

packages/api/src/controllers/leo/SearchController.ts
packages/api/src/controllers/record/RecordsController.ts
packages/client/locales/en/common.json
packages/client/package.json
packages/client/src/components/active-bolos/ManageBoloModal.tsx
packages/client/src/components/form/InputSuggestions.tsx
packages/client/src/components/leo/modals/CreateTicketModal.tsx
packages/client/src/components/leo/modals/CreateWarrantModal.tsx
packages/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
packages/schemas/src/records.ts
yarn.lock

:tada: suggested input

---

.github/workflows/test-build.yml
packages/client/package.json
packages/client/src/components/bleeter/ManageBleetModal.tsx
packages/client/src/components/ems-fd/modals/ManageDeputyModal.tsx
packages/client/src/components/leo/modals/ManageOfficerModal.tsx
packages/client/src/components/modal/CropImageModal.tsx
packages/client/src/components/modal/Modal.tsx
packages/client/src/pages/_app.tsx
packages/client/src/pages/citizen/[id]/edit.tsx
packages/client/src/pages/citizen/create.tsx
packages/client/src/types/ModalIds.ts
yarn.lock

:tada: add back cropper

---

packages/api/src/controllers/citizen/TruckLogsController.ts
packages/api/src/controllers/leo/SearchController.ts
packages/client/package.json
packages/client/src/components/citizen/MedicalRecords.tsx
packages/client/src/components/citizen/VehiclesCard.tsx
packages/client/src/components/citizen/WeaponsCard.tsx
packages/client/src/components/dispatch/ActiveDeputies.tsx
packages/client/src/components/dispatch/ModalButtons.tsx
packages/client/src/components/dispatch/modals/AddressSearchModal.tsx
packages/client/src/components/ems-fd/modals/CreateMedicalRecord.tsx
packages/client/src/components/ems-fd/modals/SearchMedicalRecords.tsx
packages/client/src/components/leo/modals/NameSearchModal/RecordsArea.tsx
packages/client/src/components/leo/modals/NameSearchModal/VehiclesAndWeapons.tsx
packages/client/src/components/table/Table.tsx
packages/client/src/pages/admin/manage/units/[id].tsx
packages/client/src/pages/admin/manage/units/index.tsx
packages/client/src/pages/ems-fd/my-deputies.tsx
packages/client/src/pages/officer/impound-lot.tsx
packages/client/src/pages/officer/incidents.tsx
packages/client/src/pages/officer/my-officer-logs.tsx
packages/client/src/pages/officer/my-officers.tsx
packages/client/src/pages/taxi.tsx
packages/client/src/pages/tow/index.tsx
packages/client/src/pages/tow/logs.tsx
packages/client/src/pages/truck-logs.tsx
packages/client/src/state/dispatchState.ts
packages/client/src/styles/globals.scss
packages/client/src/types/prisma.ts
yarn.lock

- ~~[ ] `ActiveOfficers`~~
- ~~[ ] `ActiveCalls`~~

:tada: react-table migration

---

packages/client/src/lib/useFetch.tsx

:hammer: log useful error data to console for debugging

---

packages/api/src/controllers/dispatch/StatusController.ts
packages/api/src/lib/ems-fd.ts
packages/api/src/lib/officer.ts
packages/client/src/components/shared/StatusesArea.tsx
packages/client/src/types/prisma.ts
packages/config/src/index.ts

✨ improve active units behaviour

---

packages/api/prisma/migrations/20211219152524_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/calls/TaxiController.ts
packages/api/src/controllers/calls/TowController.ts
packages/api/src/controllers/dispatch/Calls911Controller.ts
packages/client/locales/en/calls.json
packages/client/src/components/citizen/tow/ManageTowCall.tsx
packages/client/src/components/dispatch/modals/CallTowModal.tsx
packages/client/src/components/form/FormRow.tsx
packages/client/src/components/modals/Manage911CallModal.tsx
packages/client/src/pages/taxi.tsx
packages/client/src/pages/tow/index.tsx
packages/client/src/pages/tow/logs.tsx
packages/client/src/types/prisma.ts

🎉 add postal to calls

---

packages/api/prisma/migrations/20211222082436_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/CadSettings.ts
packages/api/src/services/SocketService.ts
packages/client/locales/en/common.json
packages/client/src/components/Layout.tsx
packages/client/src/components/admin/AdminLayout.tsx
packages/client/src/hooks/useRoleplayStopped.tsx
packages/client/src/pages/admin/manage/cad-settings.tsx
packages/client/src/pages/officer/incidents.tsx
packages/client/src/types/prisma.ts
packages/config/src/socket-events.ts

:tada: feat: stop roleplay feature

---

packages/api/src/controllers/dispatch/Calls911Controller.ts
packages/client/locales/en/common.json
packages/client/src/components/active-bolos/ManageBoloModal.tsx
packages/client/src/components/admin/manage/MiscFeatures.tsx
packages/client/src/components/admin/values/ManageValueModal.tsx
packages/client/src/components/bleeter/ManageBleetModal.tsx
packages/client/src/components/citizen/modals/RegisterVehicleModal.tsx
packages/client/src/components/citizen/modals/RegisterWeaponModal.tsx
packages/client/src/components/dispatch/modals/CallTowModal.tsx
packages/client/src/components/ems-fd/modals/ManageDeputyModal.tsx
packages/client/src/components/form/FormField.tsx
packages/client/src/components/leo/ModalButtons.tsx
packages/client/src/components/leo/modals/CreateTicketModal.tsx
packages/client/src/components/leo/modals/ManageOfficerModal.tsx
packages/client/src/pages/admin/manage/cad-settings.tsx
packages/client/src/pages/admin/manage/users/[id].tsx
packages/client/src/pages/citizen/[id]/edit.tsx
packages/client/src/pages/citizen/create.tsx
packages/schemas/src/admin/index.ts

:tada: feat: optional form fields

---

packages/client/locales/en/values.json
packages/client/src/components/admin/values/ManageValueModal.tsx
packages/client/src/components/admin/values/SortableList.tsx
packages/client/src/components/table/Table.tsx
packages/client/src/lib/admin/values.ts
packages/client/src/pages/admin/values/[path].tsx
packages/client/src/types/prisma.ts

:tada: feat: new values UI

---

packages/api/src/controllers/admin/values/Import.ts
packages/client/locales/en/values.json
packages/client/src/components/admin/values/ImportValuesModal.tsx
packages/client/src/components/admin/values/OptionsDropdown.tsx
packages/client/src/pages/admin/values/[path].tsx
packages/client/src/types/ModalIds.ts
packages/schemas/src/admin/values/import.ts
packages/schemas/src/index.ts
packages/schemas/src/lib/validate.ts

:tada: feat: support for file import

---

packages/api/prisma/migrations/20211228091734_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/Values.ts
packages/api/src/controllers/admin/values/PenalCodeGroup.ts
packages/client/locales/en/common.json
packages/client/locales/en/values.json
packages/client/src/components/admin/values/ManagePenalCode.tsx
packages/client/src/components/admin/values/ManagePenalCodeGroup.tsx
packages/client/src/pages/admin/values/[path].tsx
packages/client/src/pages/admin/values/penal-code.tsx
packages/client/src/types/ModalIds.ts
packages/client/src/types/prisma.ts
packages/schemas/src/admin/values.ts

:sparkles: Grouped penal codes

---

packages/api/src/controllers/leo/LeoController.ts
packages/client/locales/en/leo.json
packages/client/src/components/form/FormField.tsx
packages/client/src/components/leo/modals/NameSearchModal/EditCitizenLicensesModal.tsx
packages/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
packages/client/src/pages/dispatch/index.tsx
packages/client/src/pages/officer/index.tsx
packages/client/src/types/ModalIds.ts

🎉 feat: allow editing licenses (LEO/dispatch)

---

.github/workflows/cancel.yml

:hammer: add cancel previous runs workflow

---

packages/client/src/components/admin/AdminLayout.tsx
packages/client/src/components/admin/Sidebar.tsx
packages/client/src/components/table/Table.tsx
packages/client/src/pages/admin/values/[path].tsx
packages/client/src/styles/globals.scss

:hammer: chore: improve admin UI

---

packages/client/src/components/admin/manage/DisabledFeatures.tsx

:hammer: improve features tab

---

packages/client/locales/en/admin.json
packages/client/locales/en/leo.json
packages/client/src/components/dispatch/map/Map.tsx
packages/client/src/pages/admin/index.tsx
packages/client/src/pages/dispatch/map.tsx

:hammer: fix: add missing translations

---

packages/api/src/controllers/auth/Auth.ts
packages/api/src/lib/auth.ts
packages/client/package.json
packages/client/src/lib/fetch.ts
packages/client/src/lib/utils.ts
packages/client/src/pages/api/token.ts
packages/client/src/pages/auth/login.tsx
packages/client/src/pages/auth/register.tsx
yarn.lock

✨ feat: initial iframe support

---

.gitignore
packages/client/src/pages/_document.tsx

:tada: feat: support for favicon

---

packages/api/src/controllers/leo/SearchController.ts
packages/api/src/controllers/record/RecordsController.ts
packages/client/locales/en/leo.json
packages/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
packages/client/src/components/leo/modals/NameSearchModal/RecordsArea.tsx
packages/client/src/state/nameSearchState.ts
packages/client/src/types/ModalIds.ts

:tada: feat: able to revoke warrants

---

packages/api/src/controllers/leo/LeoController.ts
packages/api/src/services/SocketService.ts
packages/client/src/hooks/usePanicButton.tsx
packages/config/src/socket-events.ts

🐛 fix: able to unset panic-button

---

packages/api/src/controllers/dispatch/Calls911Controller.ts
packages/client/src/components/table/Table.tsx
packages/client/src/pages/officer/call-history.tsx
packages/client/src/types/ModalIds.ts

:tada: feat: allow purging 911-calls

---

packages/client/next.config.js
packages/client/src/pages/index.tsx

:hammer: chore: redirect instantly to /auth/login when not-authenicated

---

packages/api/src/controllers/leo/SearchController.ts
packages/client/locales/en/leo.json
packages/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
packages/client/src/components/leo/modals/VehicleSearchModal.tsx

:tada: feat: suggested search

---

packages/api/src/controllers/dispatch/BoloController.ts
packages/client/src/components/leo/modals/VehicleSearchModal.tsx

:bug: fix: only send required data for mark-stolen

---

packages/client/package.json
packages/client/src/components/account/AppearanceTab.tsx
packages/client/src/components/form/Select.tsx
packages/client/src/components/form/select/MultiValueContainerContextMenu.tsx
packages/client/src/components/form/select/MultiValueContainerPenalCode.tsx
packages/client/src/components/leo/modals/CreateTicketModal.tsx
packages/client/src/components/modals/Manage911CallModal.tsx
yarn.lock

:tada: feat: add penal code popup

---

packages/api/src/controllers/auth/User.ts
packages/api/src/controllers/dispatch/Calls911Controller.ts
packages/api/src/controllers/dispatch/StatusController.ts
packages/api/src/services/SocketService.ts
packages/client/package.json
packages/client/src/components/admin/manage/PendingUsersTab.tsx
packages/client/src/components/admin/values/ManagePenalCode.tsx
packages/client/src/components/courthouse/RequestExpungement.tsx
packages/client/src/components/form/InputSuggestions.tsx
packages/client/src/components/modal/Modal.tsx
packages/client/src/components/table/Table.tsx
packages/client/src/pages/admin/manage/units/index.tsx
packages/client/src/pages/admin/manage/users/index.tsx
packages/client/src/pages/admin/values/penal-code.tsx
yarn.lock

-  hide \<Select/\> when citizen doesn't have X in request expungement.
- Allow disabling columns sorting by columnId
- Show table instead of list for users
- Increase min-height for \<ManagePenalCode/\>
- Update 911 calls when unit set off-duty (realtime)
- Set max-width for penal codes table
- Set officers off-duty when logging out

🔨 refactor: refactor code

---

packages/api/prisma/migrations/20220107063437_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/citizen/CitizenController.ts
packages/client/locales/en/citizen.json
packages/client/src/components/citizen/modals/ManageOccupationModal.tsx
packages/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
packages/client/src/pages/citizen/[id]/index.tsx
packages/client/src/types/ModalIds.ts
packages/client/src/types/prisma.ts

:tada: feat: occupation

---

packages/api/prisma/migrations/20220107095706_/migration.sql
packages/api/prisma/migrations/20220107105017_/migration.sql
packages/api/prisma/migrations/20220107123346_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/Businesses.ts
packages/api/src/controllers/admin/manage/CadSettings.ts
packages/api/src/controllers/admin/values/Import.ts
packages/api/src/controllers/business/BusinessController.ts
packages/api/src/controllers/business/EmployeeController.ts
packages/api/src/controllers/business/PostsController.ts
packages/api/src/middlewares/IsAuth.ts
packages/api/src/utils/businesses.ts
packages/client/locales/en/admin.json
packages/client/locales/en/business.json
packages/client/locales/en/common.json
packages/client/src/components/admin/manage/business/PendingBusinessesTab.tsx
packages/client/src/components/business/BusinessCard.tsx
packages/client/src/components/business/CreateBusinessModal.tsx
packages/client/src/components/business/JoinBusinessModal.tsx
packages/client/src/pages/admin/manage/businesses.tsx
packages/client/src/pages/admin/manage/cad-settings.tsx
packages/client/src/pages/business/[id]/[employeeId]/index.tsx
packages/client/src/pages/business/index.tsx
packages/client/src/pages/citizen/[id]/index.tsx
packages/client/src/types/prisma.ts

:tada: feat: business whitelisted

---

packages/client/src/components/tabs/TabsContainer.tsx

✨  feat: improve tabs design

---

packages/client/src/components/leo/modals/CreateRecord/SelectPenalCode.tsx
packages/client/src/components/leo/modals/CreateTicketModal.tsx
packages/client/src/context/ValuesContext.tsx

https://user-images.githubusercontent.com/53900565/148548924-80979d79-9382-4605-9ccd-2e8643c336ea.mov

🎉 feat: able to filter by group

---

.github/workflows/test-build.yml

:hammer: ci: add Next.js cache

---

packages/api/prisma/migrations/20220108103934_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/CadSettings.ts
packages/api/src/controllers/admin/manage/cad-settings/CADImagesController.ts
packages/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
packages/client/src/components/active-bolos/ActiveBolos.tsx
packages/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx
packages/client/src/components/auth/AuthScreenImages.tsx
packages/client/src/components/form/inputs/ImageSelectInput.tsx
packages/client/src/pages/auth/login.tsx
packages/client/src/pages/auth/register.tsx
packages/client/src/types/prisma.ts

🎉 feat: allow uploading auth images

---

packages/api/prisma/migrations/20220109070928_/migration.sql
packages/api/prisma/schema.prisma

:hammer: fix(prisma): `CASCADE` user references

---

packages/api/prisma/migrations/20220108084554_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/Citizens.ts
packages/api/src/controllers/admin/manage/Units.ts
packages/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
packages/api/src/controllers/citizen/CitizenController.ts
packages/api/src/controllers/dispatch/BoloController.ts
packages/api/src/controllers/dispatch/Calls911Controller.ts
packages/api/src/controllers/dispatch/StatusController.ts
packages/api/src/controllers/leo/IncidentController.ts
packages/api/src/controllers/leo/JailController.ts
packages/api/src/controllers/leo/LeoController.ts
packages/api/src/controllers/leo/SearchController.ts
packages/api/src/lib/officer.ts
packages/api/src/lib/prisma.ts
packages/api/src/migrations/divisionToDivisions.ts
packages/client/locales/en/common.json
packages/client/locales/en/leo.json
packages/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx
packages/client/src/components/dispatch/ActiveDeputies.tsx
packages/client/src/components/dispatch/ActiveOfficers.tsx
packages/client/src/components/leo/modals/ManageOfficerModal.tsx
packages/client/src/hooks/useGenerateCallsign.ts
packages/client/src/lib/utils.ts
packages/client/src/pages/admin/manage/units/[id].tsx
packages/client/src/pages/admin/manage/units/index.tsx
packages/client/src/pages/officer/my-officers.tsx
packages/client/src/types/prisma.ts
packages/schemas/src/admin/index.ts
packages/schemas/src/leo.ts

🎉  feat: allow mutiple divisions for officers

---

packages/api/prisma/migrations/20220110184116_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/business/BusinessController.ts
packages/api/src/controllers/citizen/CitizenController.ts
packages/client/locales/en/common.json
packages/client/src/components/business/CreateBusinessModal.tsx
packages/client/src/components/business/manage/BusinessTab.tsx
packages/client/src/components/dispatch/modals/AddressSearchModal.tsx
packages/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
packages/client/src/lib/utils.ts
packages/client/src/pages/admin/manage/citizens.tsx
packages/client/src/pages/citizen/[id]/edit.tsx
packages/client/src/pages/citizen/[id]/index.tsx
packages/client/src/pages/citizen/create.tsx
packages/client/src/types/prisma.ts
packages/schemas/src/businesses.ts

:tada: feat: add postal to more locations

---

packages/api/src/controllers/citizen/CitizenController.ts
packages/client/src/components/citizen/ManageCitizenForm.tsx
packages/client/src/pages/citizen/[id]/edit.tsx
packages/client/src/pages/citizen/create.tsx

:hammer: chore: minor refactor

---

.env.example
packages/api/src/controllers/auth/Auth.ts
packages/api/src/lib/auth.ts
packages/api/src/utils/setCookie.ts
packages/client/package.json
packages/client/src/lib/fetch.ts
packages/client/src/pages/api/token.ts
packages/client/src/pages/auth/login.tsx
packages/client/src/pages/auth/register.tsx
yarn.lock

Revert "🔨 remove experimental stuff"

---

packages/api/prisma/migrations/20220116084744_/migration.sql
packages/api/prisma/schema.prisma

:bug: fix: unable to delete citizen

---

package.json
packages/client/locales/en/leo.json
packages/client/src/pages/officer/supervisor/citizen-logs.tsx
patches/@tsed+schema+6.98.0.patch
yarn.lock

:bug: fix: add patch-package to temp-fix bug in `@tsed/schema`

---

packages/api/src/controllers/leo/IncidentController.ts
packages/client/src/components/leo/modals/ManageIncidentModal.tsx
packages/client/src/pages/officer/incidents.tsx
packages/client/src/types/ModalIds.ts

🎉  feat: allow editing LEO incidents

---

packages/api/package.json
packages/api/src/controllers/auth/Discord.ts
packages/api/src/lib/discord.ts
packages/api/src/utils/callsign.ts
yarn.lock

- also fixes a bug where it would not send webhook because of a typeerror

:hammer: chore: replace node-fetch with undici

---

packages/api/prisma/migrations/20220121131926_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
packages/api/src/controllers/leo/LeoController.ts
packages/client/locales/en/common.json
packages/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx
packages/client/src/types/prisma.ts
packages/schemas/src/admin/index.ts

:tada: feat: max limit of officers per user

---

packages/client/src/components/admin/AdminLayout.tsx
packages/client/src/components/admin/Sidebar.tsx
packages/client/src/pages/admin/index.tsx
packages/client/src/pages/admin/manage/businesses.tsx
packages/client/src/pages/admin/manage/cad-settings.tsx
packages/client/src/pages/admin/manage/citizens.tsx
packages/client/src/pages/admin/manage/expungement-requests/index.tsx
packages/client/src/pages/admin/manage/units/[id].tsx
packages/client/src/pages/admin/manage/units/index.tsx
packages/client/src/pages/admin/manage/users/[id].tsx
packages/client/src/pages/admin/manage/users/index.tsx
packages/client/src/pages/admin/values/[path].tsx
packages/client/src/pages/admin/values/driverslicense-category.tsx
packages/client/src/pages/admin/values/penal-code.tsx

:tada: feat: improve admin's sidebar

---

packages/api/src/controllers/leo/LeoController.ts
packages/client/src/components/leo/ModalButtons.tsx

🎉 feat: make panic-button work with API token

---

packages/api/src/controllers/admin/manage/Citizens.ts
packages/client/src/components/admin/manage/citizens/AdvancedCitizensTab.tsx
packages/client/src/components/admin/manage/citizens/ImportCitizensModal.tsx
packages/client/src/types/ModalIds.ts
packages/schemas/src/admin/index.ts

🎉 feat: able to import citizens via file

---

packages/api/prisma/migrations/20220125150836_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/Values.ts
packages/api/src/controllers/admin/values/Import.ts
packages/client/locales/en/values.json
packages/client/src/components/admin/values/ManageValueModal.tsx
packages/client/src/components/citizen/ManageCitizenForm.tsx
packages/client/src/components/citizen/licenses/ManageLicensesModal.tsx
packages/client/src/components/citizen/vehicles/RegisterVehicleModal.tsx
packages/client/src/components/citizen/weapons/RegisterWeaponModal.tsx
packages/client/src/components/leo/modals/NameSearchModal/EditCitizenLicensesModal.tsx
packages/client/src/lib/admin/values.ts
packages/client/src/lib/utils.ts
packages/client/src/types/prisma.ts
packages/schemas/src/admin/values/import.ts

:tada: feat: able to separate licenses

---

packages/api/src/controllers/auth/Discord.ts
packages/api/src/controllers/auth/User.ts
packages/client/locales/en/common.json
packages/client/src/components/account/AccountSettingsTab.tsx

:tada: feat: make discordId field writable

---

packages/api/prisma/migrations/20220127091323_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/Citizens.ts
packages/api/src/controllers/calls/TaxiController.ts
packages/api/src/controllers/calls/TowController.ts
packages/api/src/controllers/citizen/CitizenController.ts
packages/api/src/controllers/citizen/LicenseController.ts
packages/api/src/controllers/citizen/MedicalRecordController.ts
packages/api/src/controllers/citizen/VehiclesController.ts
packages/api/src/controllers/citizen/WeaponController.ts
packages/api/src/controllers/court/CourtController.ts
packages/api/src/controllers/dispatch/Calls911Controller.ts
packages/api/src/lib/auth.ts

:hammer: refactor: remove redandunt userId properties

---

packages/client/src/components/admin/manage/citizens/AllCitizensTab.tsx
packages/client/src/components/citizen/vehicles/VehiclesCard.tsx
packages/client/src/components/citizen/weapons/WeaponsCard.tsx
packages/client/src/components/leo/logs/OfficerLogsTable.tsx
packages/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
packages/client/src/components/leo/modals/NameSearchModal/RecordsArea.tsx
packages/client/src/components/leo/modals/NameSearchModal/VehiclesAndWeapons.tsx
packages/client/src/components/leo/modals/VehicleSearchModal.tsx
packages/client/src/components/modals/911Call/EventsArea.tsx
packages/client/src/components/modals/CallEventsModal.tsx
packages/client/src/components/shared/FullDate.tsx
packages/client/src/components/shared/HoverCard.tsx
packages/client/src/pages/admin/manage/expungement-requests/index.tsx
packages/client/src/pages/admin/values/[path].tsx
packages/client/src/pages/citizen/[id]/index.tsx
packages/client/src/pages/courthouse.tsx
packages/client/src/pages/officer/call-history.tsx
packages/client/src/pages/officer/incidents.tsx
packages/client/src/pages/officer/jail.tsx
packages/client/src/pages/officer/supervisor/citizen-logs.tsx
packages/client/src/pages/taxi.tsx
packages/client/src/pages/tow/index.tsx
packages/client/src/pages/tow/logs.tsx

:tada: feat: add full-date hovercard

---

packages/client/package.json
packages/client/src/components/modal/DescriptionModal/Editor.tsx
packages/client/src/components/modal/DescriptionModal/Toolbar.tsx
packages/client/src/lib/editor/utils.ts
packages/client/src/lib/editor/withShortcuts.ts
packages/client/src/styles/globals.scss
yarn.lock

🎉 feat: editor upgrades

---

packages/client/src/components/leo/calls/CallsFilters.tsx
packages/client/src/context/CallsFiltersContext.tsx

🎉 feat: able to filter by assignedUnits

---

package.json
packages/api/package.json
packages/client/package.json
yarn.lock

:hammer: chore: bump deps

---

packages/client/package.json
packages/client/src/components/account/2fa/Manage2FAModal.tsx
packages/client/src/components/account/AccountSettingsTab.tsx
packages/client/src/components/account/AppearanceTab.tsx
packages/client/src/components/account/ConnectionsTab.tsx
packages/client/src/components/admin/manage/business/PendingBusinessesTab.tsx
packages/client/src/components/admin/manage/cad-settings/ApiTokenTab.tsx
packages/client/src/components/admin/manage/citizens/AllCitizensTab.tsx
packages/client/src/components/admin/manage/units/AllUnitsTab.tsx
packages/client/src/components/admin/manage/units/DepartmentWhitelistingTab.tsx
packages/client/src/components/admin/manage/users/PendingUsersTab.tsx
packages/client/src/components/business/manage/BusinessTab.tsx
packages/client/src/components/business/manage/EmployeesTab.tsx
packages/client/src/components/business/manage/PendingEmployeesTab.tsx
packages/client/src/components/business/manage/VehiclesTab.tsx
packages/client/src/components/shared/TabList.tsx
packages/client/src/pages/account.tsx
packages/client/src/pages/admin/manage/businesses.tsx
packages/client/src/pages/admin/manage/cad-settings.tsx
packages/client/src/pages/admin/manage/citizens/index.tsx
packages/client/src/pages/admin/manage/units/index.tsx
packages/client/src/pages/admin/manage/users/index.tsx
packages/client/src/pages/business/[id]/[employeeId]/manage.tsx
packages/client/src/styles/globals.scss
yarn.lock

- General improvements to businesses
- Improved tab lists a11y thanks to [Radix UI](https://radix-ui.com)

🔨 chore: improve TabList code

---

packages/api/prisma/migrations/20220205112402_/migration.sql
packages/api/prisma/migrations/20220205123934_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/auth/User.ts
packages/api/src/lib/auth.ts
packages/client/src/components/account/AppearanceTab.tsx
packages/client/src/components/citizen/medical-records/MedicalRecords.tsx
packages/client/src/components/citizen/vehicles/VehiclesCard.tsx
packages/client/src/components/citizen/weapons/WeaponsCard.tsx
packages/client/src/components/dispatch/ActiveDeputies.tsx
packages/client/src/components/leo/ActiveCalls.tsx
packages/client/src/components/shared/Table.tsx
packages/client/src/components/shared/Table/TableProps.ts
packages/types/src/index.ts

🎉 feat: add table actions alignment

---

packages/api/src/controllers/admin/manage/Units.ts
packages/client/src/pages/admin/manage/units/[id].tsx
packages/schemas/src/leo.ts

:tada: feat: able to update more unit data

---

packages/api/src/controllers/admin/Values.ts
packages/api/src/controllers/admin/values/Import.ts
packages/client/src/components/admin/values/import/ImportValuesModal.tsx
packages/client/src/lib/error.tsx

:hammer: chore: improve import error handling

---

packages/client/src/components/account/AccountSettingsTab.tsx
packages/client/src/components/account/AppearanceTab.tsx
packages/client/src/components/dispatch/ActiveOfficers.tsx
packages/client/src/components/shared/Table.tsx

:hammer: chore: use `Table` component

---

packages/client/locales/en/auth.json
packages/client/package.json
packages/client/src/components/account/AccountSettingsTab.tsx
packages/client/src/components/auth/TwoFactorAuthScreen.tsx
packages/client/src/pages/auth/login.tsx
yarn.lock

:tada: feat: improved 2FA login flow

---

packages/client/src/components/dispatch/ActiveOfficers.tsx
packages/client/src/components/shared/Table.tsx
packages/client/src/hooks/realtime/useActiveOfficers.ts

:bug: fix: set correct activeofficer on unmerge

---

packages/client/src/components/modal/DescriptionModal/ChecklistItem.tsx
packages/client/src/components/modal/DescriptionModal/Editor.tsx
packages/client/src/components/modal/DescriptionModal/Toolbar.tsx
packages/client/src/components/modal/DescriptionModal/types.ts
packages/client/src/lib/editor/utils.ts
packages/client/src/lib/editor/withChecklists.ts
packages/client/src/lib/editor/withShortcuts.ts

:tada: feat: add checkboxes to Editor

---

packages/api/src/controllers/admin/Values.ts
packages/client/locales/en/values.json
packages/client/src/components/shared/Table.tsx
packages/client/src/pages/admin/values/[path].tsx
packages/client/src/types/ModalIds.ts

🎉 feat: able to select table items in values

---

.env.example
package.json
scripts/copy-env.mjs
yarn.lock

custom port option

---

packages/api/src/controllers/admin/Values.ts
packages/api/src/controllers/admin/values/Import.ts
packages/api/src/lib/records/penal-code.ts
packages/client/src/components/admin/values/import/OptionsDropdown.tsx
packages/client/src/components/admin/values/penal-codes/ManagePenalCode.tsx
packages/client/src/components/admin/values/penal-codes/ManagePenalCodeGroup.tsx
packages/client/src/components/modal/DescriptionModal/Editor.tsx
packages/client/src/pages/admin/values/penal-code.tsx
packages/schemas/src/admin/values/import.ts

🎉 feat: import penal-codes

---

packages/api/prisma/migrations/20220214151127_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
packages/api/src/controllers/ems-fd/EmsFdController.ts
packages/api/src/controllers/leo/LeoController.ts
packages/client/locales/en/common.json
packages/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx
packages/client/src/components/leo/modals/ManageOfficerModal.tsx
packages/schemas/src/admin/index.ts
packages/types/src/index.ts

:tada: feat: able to set max departments per unit per user

---

packages/api/prisma/migrations/20220219064214_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/Users.ts
packages/api/src/controllers/admin/manage/cad-settings/discord/DiscordSettingsController.ts
packages/api/src/controllers/auth/Discord.ts
packages/api/src/lib/discord/admin.ts
packages/api/src/lib/discord/auth.ts
packages/client/src/components/admin/manage/cad-settings/DiscordRolesTab.tsx
packages/client/src/pages/admin/manage/users/index.tsx
packages/schemas/src/admin/index.ts
packages/types/src/index.ts

:tada: feat: discord whitelisted role

---

packages/api/prisma/migrations/20220220065106_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/Businesses.ts
packages/api/src/controllers/admin/manage/Citizens.ts
packages/api/src/controllers/admin/manage/Users.ts
packages/api/src/controllers/auth/Discord.ts
packages/api/src/controllers/auth/User.ts
packages/api/src/controllers/calls/TaxiController.ts
packages/api/src/controllers/calls/TowController.ts
packages/api/src/controllers/citizen/CitizenController.ts
packages/api/src/controllers/citizen/LicenseController.ts
packages/api/src/controllers/citizen/MedicalRecordController.ts
packages/api/src/controllers/citizen/VehiclesController.ts
packages/api/src/controllers/citizen/WeaponController.ts
packages/api/src/lib/auth/user.ts
packages/api/src/lib/cad.ts
packages/api/src/lib/officer.ts
packages/api/src/middlewares/ActiveDeputy.ts
packages/api/src/middlewares/ActiveOfficer.ts
packages/api/src/middlewares/IsAuth.ts

:hammer: chore: sync Discord every 3min/request

---

packages/client/package.json
packages/client/src/components/nav/Nav.tsx
packages/client/src/components/nav/dropdowns/DispatchDropdown.tsx
packages/client/src/components/nav/dropdowns/EmsFdDropdown.tsx
packages/client/src/components/nav/dropdowns/OfficerDropdown.tsx
packages/client/src/components/nav/dropdowns/TowDropdown.tsx
packages/client/tailwind.config.js
yarn.lock

Ref #435
https://user-images.githubusercontent.com/53900565/154855937-60117689-c612-4dbc-9eb5-8b28762d83ce.mov

:tada: feat: responsive mobile nav

---

packages/api/src/controllers/admin/import/ImportCitizensController.ts
packages/api/src/controllers/admin/import/ImportVehiclesController.ts
packages/api/src/controllers/admin/import/ImportWeaponsController.ts
packages/schemas/src/admin/import/citizens.ts
packages/schemas/src/admin/index.ts

:tada: feat: able to import vehicles/weapons via citizen import

---

packages/api/src/controllers/admin/import/ImportCitizensController.ts
packages/schemas/src/admin/import/citizens.ts

:tada: feat: ability to add licenses via import

---

packages/client/locales/en_gb/citizen.json
packages/client/locales/en_gb/common.json

Update to en_gb in line with new additions to en.

:hammer: chore: update en_gb in line with en

---

packages/api/prisma/migrations/20220224171140_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/Values.ts
packages/api/src/controllers/admin/values/Import.ts
packages/client/locales/en/values.json
packages/client/src/components/admin/values/ManageValueModal.tsx
packages/client/src/components/admin/values/manage-modal/DepartmentFields.tsx
packages/client/src/components/admin/values/manage-modal/StatusValueFields.tsx
packages/client/src/components/dispatch/modals/ManageUnit.tsx
packages/client/src/components/shared/StatusesArea.tsx
packages/client/src/lib/admin/values.tsx
packages/client/src/pages/officer/index.tsx
packages/schemas/src/admin/values/import.ts
packages/types/src/index.ts

:tada: feat: able to set departments for 10 codes

---

packages/api/src/controllers/admin/Values.ts
packages/api/src/controllers/admin/manage/AdminNameChangeController.ts
packages/api/src/controllers/auth/Discord.ts
packages/api/src/controllers/citizen/CitizenController.ts
packages/api/src/controllers/citizen/VehiclesController.ts
packages/api/src/lib/auth/user.ts
packages/api/src/lib/cad.ts
packages/api/src/lib/values/types.ts
packages/client/src/components/citizen/ManageCitizenForm.tsx
packages/schemas/src/citizen.ts
packages/utils/src/callsign.ts
scripts/bump-version.mjs

:hammer: chore: refactor API code

---

packages/api/prisma/migrations/20220228062318_situation_code_incident/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/dispatch/DispatchController.ts
packages/api/src/controllers/leo/incidents/IncidentController.ts
packages/api/src/controllers/leo/incidents/IncidentEventsController.ts
packages/client/locales/en/leo.json
packages/client/src/components/dispatch/ActiveIncidents.tsx
packages/client/src/components/leo/incidents/ManageIncidentModal.tsx
packages/client/src/pages/officer/incidents.tsx
packages/schemas/src/leo.ts
packages/types/src/index.ts

:tada: feat: able to connect situation codes to incidents

---

packages/api/prisma/migrations/20220228155753_leo_roles_discord/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/cad-settings/discord/DiscordSettingsController.ts
packages/api/src/lib/discord/admin.ts
packages/api/src/lib/discord/auth.ts
packages/api/src/lib/prisma.ts
packages/api/src/middlewares/IsAuth.ts
packages/api/src/migrations/leoRoleToLeoRoles.ts
packages/client/src/components/admin/manage/cad-settings/DiscordRolesTab.tsx
packages/schemas/src/admin/index.ts
packages/types/src/index.ts

:tada: feat: allow specifying multiple Discord roles for LEO permission

---

packages/api/src/controllers/admin/Values.ts
packages/api/src/controllers/admin/values/Import.ts
packages/api/src/controllers/citizen/CitizenController.ts
packages/client/locales/en/values.json
packages/client/src/components/admin/values/ManageValueModal.tsx
packages/client/src/components/admin/values/manage-modal/LicenseFields.tsx
packages/client/src/lib/admin/values.tsx
packages/schemas/src/admin/values.ts
packages/schemas/src/admin/values/import.ts

:tada: feat: default citizen license

---

packages/client/locales/en/common.json
packages/client/src/components/dispatch/ActiveDeputies.tsx
packages/client/src/components/dispatch/ActiveOfficers.tsx
packages/client/src/components/dispatch/active-units/ActiveUnitsSearch.tsx
packages/client/src/state/activeUnitsState.ts

🎉  feat: active unit search

---

packages/client/src/components/dispatch/ActiveDeputies.tsx
packages/client/src/components/dispatch/ActiveOfficers.tsx
packages/client/src/hooks/shared/useActiveUnitsFilter.ts
packages/utils/src/callsign.ts

:bug: fix: remove duplicated column

---

packages/api/src/controllers/dispatch/StatusController.ts
packages/client/src/components/admin/manage/units/AllUnitsTab.tsx
packages/client/src/components/dispatch/ActiveOfficers.tsx
packages/client/src/components/dispatch/active-units/UnitRadioChannelModal.tsx
packages/client/src/components/dispatch/active-units/officers/OfficerColumn.tsx
packages/client/src/components/dispatch/modals/ManageUnit.tsx
packages/client/src/components/form/select/MultiValueContainerContextMenu.tsx
packages/client/src/components/leo/ActiveCalls.tsx
packages/client/src/components/modals/Manage911CallModal.tsx
packages/client/src/hooks/shared/useActiveUnitsFilter.ts
packages/client/src/hooks/shared/usePanicButton.tsx
packages/client/src/lib/utils.ts
packages/client/src/pages/admin/manage/units/[id].tsx
packages/client/src/pages/officer/call-history.tsx

:hammer: chore: refactor "x" in y

---

packages/api/prisma/migrations/20220306075835_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/citizen/CitizenController.ts
packages/api/src/controllers/citizen/VehiclesController.ts
packages/api/src/controllers/leo/SearchController.ts
packages/client/src/components/admin/values/ManageValueModal.tsx
packages/client/src/components/admin/values/manage-modal/LicenseFields.tsx
packages/client/src/components/citizen/vehicles/RegisterVehicleModal.tsx
packages/client/src/components/citizen/vehicles/VehiclesCard.tsx
packages/client/src/components/leo/modals/VehicleSearchModal.tsx
packages/schemas/src/admin/values/import.ts
packages/schemas/src/citizen.ts
packages/types/src/index.ts

:tada: feat: add vehicle insurance status

---

packages/api/src/controllers/admin/import/ImportCitizensController.ts
packages/api/src/controllers/admin/manage/Units.ts
packages/api/src/controllers/admin/values/Import.ts
packages/api/src/controllers/citizen/CitizenController.ts
packages/api/src/controllers/citizen/LicenseController.ts
packages/api/src/controllers/leo/LeoController.ts
packages/api/src/utils/manyToMany.ts
packages/client/src/components/citizen/ManageCitizenForm.tsx

:hammer: chore: many-to-many helper

---

packages/api/prisma/migrations/20220306164233_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/citizen/VehiclesController.ts
packages/client/locales/en/citizen.json
packages/client/src/components/citizen/vehicles/RegisterVehicleModal.tsx
packages/client/src/components/leo/modals/VehicleSearchModal.tsx
packages/schemas/src/citizen.ts
packages/types/src/index.ts

:tada: feat: add vehicle tax status & inspection status

---

packages/api/src/controllers/admin/values/Import.ts

🔨  chore: refactor import x2

---

packages/api/src/controllers/leo/LeoController.ts
packages/client/src/components/citizen/vehicles/RegisterVehicleModal.tsx
packages/client/src/components/leo/modals/VehicleSearch/ManageVehicleLicensesModal.tsx
packages/client/src/components/leo/modals/VehicleSearchModal.tsx
packages/client/src/hooks/locale/useVehicleLicenses.ts
packages/client/src/types/ModalIds.ts
packages/schemas/src/leo.ts

:tada: feat: allow LEO to manage vehicle licenses

---

packages/client/src/components/leo/incidents/ManageIncidentModal.tsx

:bug: fix: correct handle officers state

---

.github/workflows/test-builds-typecheck.yml
packages/config/package.json
packages/config/tests/index.test.ts
packages/schemas/src/citizen.ts
packages/schemas/src/records.ts
packages/schemas/src/tow.ts
packages/utils/package.json
packages/utils/tests/typeguards.test.ts
turbo.json
yarn.lock

:tada: feat: add vitest

---

.eslintrc
package.json
packages/api/src/controllers/admin/manage/courthouse/AdminManageExpungementRequests.ts
packages/api/src/controllers/admin/manage/courthouse/AdminNameChangeController.ts
packages/api/src/controllers/dispatch/CombinedUnitsController.ts
packages/api/src/lib/auth/crypto.ts
packages/api/src/lib/discord/config.ts
packages/client/src/components/shared/ContextMenu.tsx
packages/client/src/context/AuthContext.tsx
packages/client/src/context/CallsFiltersContext.tsx
packages/client/src/context/CitizenContext.tsx
packages/client/src/context/ModalContext.tsx
packages/client/src/context/ValuesContext.tsx
packages/client/src/lib/auth.ts
packages/client/src/lib/useFetch.ts
yarn.lock

🔨  chore: bump eslint packages

---

packages/client/src/components/calls/TowTaxiCallsTable.tsx
packages/client/src/components/citizen/tow/AssignToTowCall.tsx
packages/client/src/components/citizen/tow/ManageTowCall.tsx
packages/client/src/pages/taxi.tsx
packages/client/src/pages/tow/index.tsx

:hammer: chore: re-use code for taxi & tow

---

packages/api/prisma/migrations/20220314152458_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/import/ImportCitizensController.ts
packages/api/src/controllers/admin/manage/Citizens.ts
packages/api/src/controllers/citizen/CitizenController.ts
packages/api/src/controllers/citizen/LicenseController.ts
packages/api/src/controllers/leo/LeoController.ts
packages/client/locales/en/citizen.json
packages/client/src/components/citizen/ManageCitizenForm.tsx
packages/client/src/components/citizen/licenses/LicensesCard.tsx
packages/client/src/components/citizen/licenses/ManageLicensesModal.tsx
packages/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
packages/schemas/src/admin/import/citizens.ts
packages/schemas/src/admin/values/import.ts
packages/schemas/src/citizen.ts
packages/types/src/index.ts

:tada: feat: Firearm license category

---

packages/client/src/components/shared/Table.tsx
packages/client/src/components/shared/Table/IndeterminateCheckbox.tsx
packages/client/src/components/shared/Table/TableHead.tsx
packages/client/src/components/shared/Table/TablePagination.tsx
packages/client/src/components/shared/Table/TableRow.tsx
packages/client/src/lib/table/dndArrowHook.tsx
packages/client/src/lib/table/makeColumns.ts
packages/client/src/styles/globals.scss
packages/client/src/types/react-table.d.ts

:hammer: refactor: split up table component

---

packages/api/src/controllers/admin/values/ValuesController.ts
packages/client/src/components/citizen/vehicles/RegisterVehicleModal.tsx
packages/client/src/components/citizen/weapons/RegisterWeaponModal.tsx
packages/client/src/components/form/inputs/InputSuggestions.tsx
packages/client/src/pages/citizen/[id]/index.tsx
packages/client/src/pages/citizen/index.tsx

🎉 feat: Lazy load weapon & vehicle values

---

.github/workflows/test-builds-typecheck.yml
packages/api/package.json
packages/api/tests/many-to-many.test.ts
packages/api/tests/value-utils.test.ts
packages/client/package.json
packages/config/package.json
packages/permissions/package.json
packages/utils/package.json
yarn.lock

:tada: feat: add API utils tests

---

packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts
packages/api/src/controllers/leo/incidents/IncidentController.ts

:tada: feat: add /:id for incidents & calls

---

packages/api/prisma/migrations/20220404184430_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/leo/incidents/IncidentController.ts
packages/client/src/components/leo/incidents/ManageIncidentModal.tsx
packages/schemas/src/leo.ts
packages/types/src/index.ts

:tada: feat: add postal to incidents

---

packages/config/package.json
packages/permissions/package.json
packages/schemas/package.json
packages/types/package.json
packages/utils/package.json
yarn.lock

:hammer: chore: output ESM & CJS

---

packages/api/prisma/migrations/20220409062923_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/auth/User.ts
packages/client/locales/en/account.json
packages/client/src/components/Layout.tsx
packages/client/src/components/account/AppearanceTab.tsx
packages/client/src/components/admin/AdminLayout.tsx
packages/client/src/components/leo/ActiveCalls.tsx
packages/client/src/hooks/global/useRoleplayStopped.tsx
packages/types/src/index.ts

:tada: feat: Added to call & stop roleplay sounds

---

packages/api/src/controllers/leo/SearchController.ts
packages/client/locales/en/leo.json
packages/client/src/components/dispatch/ModalButtons.tsx
packages/client/src/components/leo/ModalButtons.tsx
packages/client/src/components/leo/modals/CustomFieldSearch/CustomFieldResults.tsx
packages/client/src/components/leo/modals/CustomFieldSearch/CustomFieldSearch.tsx
packages/client/src/pages/dispatch/index.tsx
packages/client/src/pages/officer/index.tsx
packages/client/src/types/ModalIds.ts
packages/schemas/src/leo.ts

:tada: feat: Custom Field Search

---

packages/client/package.json
packages/client/src/components/dispatch/ActiveDeputies.tsx
packages/client/src/components/dispatch/active-units/officers/OfficerColumn.tsx
packages/client/src/components/leo/ActiveCalls.tsx
packages/client/src/components/shared/dnd/Draggable.tsx
packages/client/src/components/shared/dnd/Droppable.tsx
packages/client/src/pages/_app.tsx
packages/client/src/types/DndActions.ts
yarn.lock

:tada: feat: drag/drop support for assigned units

---

packages/client/src/components/leo/ModalButtons.tsx
packages/permissions/src/index.ts

:tada: feat: allow LEO to make calls

---

packages/client/locales/en/common.json
packages/client/locales/en/leo.json
packages/client/src/components/nav/dropdowns/OfficerDropdown.tsx
packages/client/src/pages/admin/values/[path].tsx
packages/client/src/pages/officer/penal-codes.tsx

:tada: feat: penal codes page

---

packages/api/prisma/migrations/20220413130107_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/AdminManageUnitsController.ts
packages/api/src/controllers/admin/values/Import.ts
packages/api/src/controllers/admin/values/ValuesController.ts
packages/api/src/controllers/leo/LeoController.ts
packages/api/src/lib/leo/handleWhitelistStatus.ts
packages/client/locales/en/values.json
packages/client/src/components/admin/values/ManageValueModal.tsx
packages/client/src/components/admin/values/manage-modal/DepartmentFields.tsx
packages/client/src/lib/admin/values.tsx
packages/client/src/pages/admin/values/[path].tsx
packages/schemas/src/admin/values/import.ts
packages/types/src/index.ts

🎉  feat: able to provide default officer rank

---

packages/client/locales/en/common.json
packages/client/src/components/Layout.tsx
packages/client/src/components/admin/AdminLayout.tsx
packages/client/src/hooks/global/useSocketError.tsx

🎉 feat: socket connection error banner

---

packages/api/prisma/migrations/20220419145730_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/cad-settings/discord/DiscordWebhooksController.ts
packages/api/src/controllers/dispatch/BoloController.ts
packages/api/src/controllers/dispatch/StatusController.ts
packages/api/src/lib/discord/webhooks.ts
packages/client/src/components/admin/manage/cad-settings/DiscordWebhooksTab.tsx
packages/schemas/src/admin/index.ts
packages/types/src/index.ts

🎉 feat: support for more webhook types

---

packages/api/prisma/migrations/20220420114151_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/auth/User.ts
packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts
packages/api/src/controllers/dispatch/BoloController.ts
packages/api/src/controllers/dispatch/StatusController.ts
packages/api/src/lib/discord/config.ts
packages/api/src/lib/prisma.ts
packages/api/src/utils/checkForUpdates.ts
packages/client/locales/en/account.json
packages/client/src/components/account/AppearanceTab.tsx
packages/client/src/components/dispatch/active-units/officers/OfficerColumn.tsx
packages/client/src/components/leo/ActiveCalls.tsx
packages/client/src/components/leo/modals/ManageRecord/TableItemForm.tsx
packages/client/src/pages/admin/manage/businesses.tsx
packages/client/src/pages/admin/values/[path].tsx
packages/client/src/pages/admin/values/driverslicense-category.tsx
packages/client/src/pages/admin/values/penal-code.tsx
packages/client/src/pages/tow/logs.tsx
packages/types/src/index.ts

:tada: feat: incoming call sound

---

packages/api/prisma/migrations/20220420121656_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/values/Import.ts
packages/api/src/controllers/leo/search/SearchController.ts
packages/client/locales/en/leo.json
packages/client/src/components/admin/values/ManageValueModal.tsx
packages/client/src/components/admin/values/manage-modal/DepartmentFields.tsx
packages/client/src/components/dispatch/ModalButtons.tsx
packages/client/src/components/leo/modals/CustomFieldsArea.tsx
packages/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
packages/client/src/state/search/nameSearchState.ts
packages/schemas/src/admin/values/import.ts
packages/types/src/index.ts

:tada: feat: add support for confidential departments

---

packages/api/src/controllers/calls/TowController.ts
packages/api/src/controllers/dispatch/911-calls/CallEventsController.ts
packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts
packages/api/src/controllers/leo/DLExamsController.ts
packages/api/src/controllers/leo/incidents/IncidentEventsController.ts
packages/api/src/lib/calls/assignUnitsToCall.ts
packages/api/src/lib/calls/linkOrUnlinkCallDepartmentsAndDivisions.ts
packages/api/src/lib/discord/auth.ts
packages/api/src/services/SocketService.ts
packages/api/src/utils/manyToMany.ts
packages/api/tests/many-to-many.test.ts
packages/client/src/components/dispatch/map/RenderMapBlips.tsx
packages/client/src/components/modals/911Call/EventsArea.tsx
packages/client/src/components/modals/Manage911CallModal.tsx
packages/client/src/components/modals/events/UpdateEventForm.tsx
packages/client/src/lib/map/blips.ts
packages/config/src/socket-events.ts

:hammer: refactor: call events

---

packages/api/src/controllers/leo/search/SearchController.ts
packages/api/src/exceptions/ExtendedBadRequest.ts
packages/api/src/lib/records/validateRecordData.ts
packages/api/src/middlewares/UsePermissions.ts
packages/client/locales/en/common.json
packages/client/src/components/leo/modals/ManageRecord/TableItemForm.tsx
packages/client/src/lib/useFetch.ts

:tada: feat: improve records error handling

---

packages/api/src/controllers/admin/manage/AdminManageUnitsController.ts
packages/client/locales/en/admin.json
packages/client/src/components/admin/manage/units/AllUnitsTab.tsx
packages/client/src/components/admin/manage/units/DepartmentWhitelistingTab.tsx
packages/client/src/pages/admin/manage/units/index.tsx
packages/client/src/types/ModalIds.ts

🎉 feat: add search & delete to manage units

---

packages/api/prisma/migrations/20220427114851_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/values/Import.ts
packages/client/src/components/admin/manage/units/QualificationHoverCard.tsx
packages/client/src/components/admin/manage/units/QualificationsTable.tsx
packages/client/src/components/admin/values/ManageValueModal.tsx
packages/client/src/components/admin/values/manage-modal/QualificationFields.tsx
packages/client/src/components/leo/UnitQualificationsTable.tsx
packages/schemas/src/admin/values/import.ts
packages/types/src/index.ts

:tada: feat: add description field to qualifications

---

packages/api/src/controllers/admin/manage/AdminManageUnitsController.ts
packages/api/src/controllers/auth/user/UserController.ts
packages/api/src/controllers/dispatch/CombinedUnitsController.ts
packages/api/src/controllers/dispatch/DispatchController.ts
packages/api/src/controllers/dispatch/StatusController.ts
packages/api/src/controllers/leo/LeoController.ts
packages/api/src/controllers/leo/incidents/IncidentController.ts
packages/api/src/lib/calls/assignUnitsToCall.ts
packages/api/src/services/SocketService.ts
packages/client/src/components/shared/StatusesArea.tsx
packages/client/src/hooks/realtime/useActiveDeputies.ts
packages/client/src/hooks/realtime/useActiveOfficers.ts

:rocket: refactor: improve unit status changes

---

packages/api/prisma/migrations/20220430124313_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/dispatch/CombinedUnitsController.ts
packages/api/src/lib/leo/activeOfficer.ts
packages/client/src/hooks/realtime/useActiveOfficers.ts
packages/types/src/index.ts
packages/utils/src/callsign.ts

:rocket: refactor: support department & combined unit fixes

---

packages/api/prisma/migrations/20220503141835_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/AdminManageUnitsController.ts
packages/api/src/controllers/dispatch/CombinedUnitsController.ts
packages/api/src/controllers/dispatch/StatusController.ts
packages/api/src/controllers/ems-fd/EmsFdController.ts
packages/api/src/controllers/leo/LeoController.ts
packages/api/src/lib/leo/findNextAvailableIncremental.ts
packages/api/src/lib/leo/validateDuplicateCallsigns.ts
packages/api/src/utils/findFirstSmallestInArray.ts
packages/api/tests/smallest-int-in-array.test.ts
packages/client/locales/en/admin.json
packages/client/locales/en/common.json
packages/client/src/components/admin/Sidebar/routes.ts
packages/client/src/components/admin/manage/units/CallsignsTab.tsx
packages/client/src/components/admin/manage/units/ManageUnitCallsignModal.tsx
packages/client/src/components/leo/CallsignPreview.tsx
packages/client/src/hooks/useGenerateCallsign.ts
packages/client/src/lib/useFetch.ts
packages/client/src/pages/admin/manage/units/index.tsx
packages/client/src/types/ModalIds.ts
packages/permissions/src/defaults/admin.ts
packages/permissions/src/permissions.ts
packages/schemas/src/leo.ts
packages/types/src/index.ts
packages/utils/src/callsign.ts

:rocket: feat: improved callsign management

---

packages/api/prisma/migrations/20220505120536_whitelist_ems_fd_department/migration.sql
packages/api/prisma/migrations/20220505140647_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/AdminManageUnitsController.ts
packages/api/src/controllers/admin/values/Import.ts
packages/api/src/controllers/admin/values/ValuesController.ts
packages/api/src/controllers/ems-fd/EmsFdController.ts
packages/api/src/lib/leo/activeOfficer.ts
packages/api/src/lib/leo/handleWhitelistStatus.ts
packages/client/locales/en/admin.json
packages/client/locales/en/leo.json
packages/client/src/components/admin/manage/units/AlertDeclineOfficerModal.tsx
packages/client/src/components/admin/manage/units/AllUnitsTab.tsx
packages/client/src/components/admin/manage/units/DepartmentWhitelistingTab.tsx
packages/client/src/components/admin/values/manage-modal/DepartmentFields.tsx
packages/client/src/components/dispatch/ActiveDeputies.tsx
packages/client/src/components/ems-fd/modals/SelectDeputy.tsx
packages/client/src/components/leo/UnitDepartmentStatus.tsx
packages/client/src/components/leo/modals/SelectOfficerModal.tsx
packages/client/src/lib/utils.ts
packages/client/src/pages/admin/manage/units/index.tsx
packages/client/src/pages/ems-fd/my-deputies.tsx
packages/client/src/pages/officer/my-officers.tsx
packages/client/tests/utils.test.ts
packages/types/src/index.ts

:tada: feat: Enable whitelisting & default rank for EMS/FD (WIP)

---

packages/api/prisma/migrations/20220505141915_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/dispatch/DispatchController.ts
packages/api/src/controllers/dispatch/StatusController.ts
packages/api/src/controllers/ems-fd/EmsFdController.ts
packages/api/src/controllers/leo/LeoController.ts
packages/api/src/lib/ems-fd.ts
packages/api/src/lib/leo/activeOfficer.ts
packages/api/src/lib/leo/setInactiveUnitsOffDuty.ts
packages/api/src/lib/leo/utils.ts
packages/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx

🎉  feat: automatic unit off-duty 

---

packages/api/src/controllers/dispatch/StatusController.ts
packages/client/src/components/admin/manage/users/GiveTempPasswordModal.tsx
packages/client/src/components/admin/values/SortableList.tsx
packages/client/src/components/dispatch/active-units/officers/OfficerColumn.tsx
packages/client/src/components/dispatch/map/units/RenderMapPlayers.tsx
packages/client/src/components/form/inputs/InputSuggestions.tsx
packages/client/src/components/leo/ActiveCalls.tsx
packages/client/src/components/modal/AlertModal.tsx
packages/client/src/components/modal/Modal.tsx
packages/client/src/components/shared/StatusesArea.tsx
packages/client/src/context/ValuesContext.tsx
packages/client/src/lib/useFetch.ts
packages/client/src/pages/admin/values/[path].tsx
packages/client/src/state/modalState.ts
packages/utils/tests/callsign.test.ts

🔨 chore: refactor code

---

packages/api/src/controllers/dispatch/DispatchController.ts
packages/api/src/lib/ems-fd.ts
packages/api/src/lib/leo/activeOfficer.ts
packages/client/package.json
packages/client/src/components/dispatch/map/units/RenderMapPlayers.tsx
yarn.lock

:tada: feat: show active units on the live map

---

packages/api/prisma/migrations/20220514053844_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
packages/api/src/controllers/leo/JailController.ts
packages/api/src/lib/leo/utils.ts
packages/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx
packages/schemas/src/admin/index.ts
packages/telemetry/src/index.ts
packages/types/src/index.ts

🎉 feat: auto expire arrest reports (optional feature)

---

packages/client/locales/en/calls.json
packages/client/src/components/leo/ActiveCalls.tsx
packages/client/src/components/leo/active-calls/AssignedUnitsColumn.tsx
packages/client/src/components/shared/dnd/Draggable.tsx
packages/client/src/state/dispatchState.ts
packages/client/src/types/DndActions.ts

:tada: feat: drag and drop to unassign from 911 Call

---

packages/api/prisma/migrations/20220516165653_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/cad-settings/discord/DiscordSettingsController.ts
packages/api/src/lib/discord/admin.ts
packages/api/src/lib/discord/auth.ts
packages/api/src/middlewares/IsAuth.ts
packages/client/src/components/admin/manage/cad-settings/DiscordRolesTab.tsx
packages/permissions/src/defaults/admin.ts
packages/schemas/src/admin/index.ts
packages/types/src/index.ts

🎉 feat: courthouse Discord role sync

---

packages/api/prisma/migrations/20220519162327_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/values/Import.ts
packages/api/src/controllers/admin/values/ValuesController.ts
packages/client/src/components/admin/values/ManageValueModal.tsx
packages/client/src/components/admin/values/manage-modal/StatusValueFields.tsx
packages/client/src/lib/admin/values.tsx
packages/client/src/pages/admin/manage/units/[id].tsx
packages/client/src/pages/admin/values/[path].tsx
packages/schemas/src/admin/values/import.ts
packages/types/src/index.ts

:tada: feat: able to connect departments to rank 

---

packages/api/prisma/migrations/20220526080330_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/values/Import.ts
packages/api/src/controllers/admin/values/ValuesController.ts
packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts
packages/api/src/lib/values/utils.ts
packages/api/src/middlewares/ValidPath.ts
packages/client/locales/en/calls.json
packages/client/locales/en/values.json
packages/client/src/components/admin/Sidebar/routes.ts
packages/client/src/components/admin/values/ManageValueModal.tsx
packages/client/src/components/dispatch/modals/Manage911CallModal.tsx
packages/client/src/context/ValuesContext.tsx
packages/client/src/lib/admin/values.tsx
packages/client/src/pages/dispatch/index.tsx
packages/client/src/pages/officer/index.tsx
packages/permissions/src/permissions.ts
packages/schemas/src/admin/values/import.ts
packages/schemas/src/dispatch/911-calls.ts
packages/types/src/index.ts
packages/utils/src/typeguards.ts

🎉 feat: call types

---

packages/api/src/controllers/admin/manage/AdminManageBusinessesController.ts
packages/api/src/controllers/admin/manage/ManageUsersController.ts
packages/api/src/controllers/admin/manage/cad-settings/CADImagesController.ts
packages/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
packages/api/src/controllers/auth/user/UserController.ts
packages/api/src/controllers/business/BusinessController.ts
packages/api/src/controllers/business/EmployeeController.ts
packages/api/src/controllers/business/PostsController.ts
packages/api/src/controllers/citizen/CitizenController.ts
packages/api/src/controllers/citizen/LicenseController.ts
packages/api/src/controllers/citizen/MedicalRecordController.ts
packages/api/src/controllers/citizen/VehiclesController.ts
packages/api/src/controllers/citizen/WeaponController.ts
packages/api/src/controllers/ems-fd/EmsFdController.ts
packages/api/src/controllers/leo/LeoController.ts
packages/api/src/controllers/leo/search/SearchActionsController.ts
packages/api/src/middlewares/ActiveDeputy.ts
packages/api/src/utils/businesses.ts
packages/client/src/components/dispatch/ActiveOfficers.tsx

:hammer: refactor(api): context types

---

packages/api/prisma/migrations/20220602141240_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/court/CourthousePostsController.ts
packages/api/src/middlewares/IsEnabled.ts
packages/client/locales/en/courthouse.json
packages/client/src/components/admin/manage/cad-settings/CADFeaturesTab.tsx
packages/client/src/components/courthouse/courthouse-posts/CourthousePostsTab.tsx
packages/client/src/components/courthouse/courthouse-posts/ManageCourtPostModal.tsx
packages/client/src/pages/courthouse.tsx
packages/client/src/types/ModalIds.ts
packages/permissions/src/permissions.ts
packages/schemas/src/court.ts
packages/types/src/index.ts

🎉 feat: courthouse posts

---

packages/api/src/controllers/dispatch/StatusController.ts
packages/api/src/controllers/ems-fd/EmsFdController.ts
packages/api/src/services/SocketService.ts
packages/client/src/components/ems-fd/ModalButtons.tsx
packages/client/src/pages/ems-fd/index.tsx

🎉 feat: EMS-FD Panic button

---

.gitignore

this is an issue when updating cad if you want custom sound files

ignore sound file changes

---

packages/api/prisma/migrations/20220614122254_/migration.sql
packages/api/prisma/schema.prisma
packages/schemas/src/citizen.ts

:tada: feat: add appearance field

---

packages/client/src/components/citizen/ManageCitizenForm.tsx

🎉 feat: ability for citizens to edit SSN

---

packages/api/prisma/migrations/20220616093906_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/values/Import.ts
packages/api/src/controllers/admin/values/ValuesController.ts
packages/client/locales/en/values.json
packages/client/src/components/admin/values/ManageValueModal.tsx
packages/client/src/context/ValuesContext.tsx
packages/client/src/pages/admin/values/[path].tsx
packages/schemas/src/admin/values/import.ts
packages/types/src/index.ts

🎉 feat: ability to disable values

---

packages/api/src/controllers/admin/AdminController.ts
packages/api/src/controllers/admin/import/ImportCitizensController.ts
packages/api/src/controllers/admin/import/ImportVehiclesController.ts
packages/api/src/controllers/admin/import/ImportWeaponsController.ts
packages/api/src/controllers/admin/manage/AdminManageCitizensController.ts
packages/api/src/controllers/admin/manage/AdminManageCustomFieldsController.ts

api description and example body/schema rework

---

packages/api/src/controllers/admin/import/ImportVehiclesController.ts
packages/api/src/controllers/admin/import/ImportWeaponsController.ts
packages/client/src/pages/admin/import/vehicles.tsx
packages/client/src/pages/admin/import/weapons.tsx
packages/permissions/src/permissions.ts
packages/types/src/api/admin.ts

:tada: feat: allow admins to delete registered weapons/vehicles

---

packages/client/src/pages/admin/manage/custom-roles.tsx

fix wrong route path

---

packages/api/prisma/migrations/20220713073123_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/citizen/VehiclesController.ts
packages/schemas/src/citizen.ts

:tada: feat: vehicle appearance data

---

packages/api/src/middlewares/UsePermissions.ts

console.log that wasnt removed

---

packages/api/prisma/migrations/20220803132819_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/record/RecordsController.ts
packages/client/src/components/admin/manage/cad-settings/webhooks/DiscordWebhooksTab.tsx
packages/schemas/src/admin/index.ts
packages/types/src/enums.ts

:tada: feat: able to set warrants Discord webhook

---

.gitignore
packages/api/package.json
packages/api/src/controllers/admin/AdminController.ts
packages/api/src/controllers/admin/manage/cad-settings/CADImagesController.ts
packages/api/src/controllers/admin/values/ValuesController.ts
packages/api/src/controllers/bleeter/BleeterController.ts
packages/api/src/controllers/citizen/CitizenController.ts
packages/api/src/controllers/ems-fd/EmsFdController.ts
packages/api/src/controllers/leo/my-officers/MyOfficersController.ts
packages/api/src/utils/image.ts
yarn.lock

This should improve site performance thanks to webp images being better at optimizing themself. 
**Note:** currently used images must be re-uploaded for optimizations to take effect.

:rocket: feat: add image optimizations with Sharp

---

packages/api/src/controllers/citizen/VehiclesController.ts
packages/api/src/controllers/citizen/WeaponController.ts
packages/client/locales/en/common.json
packages/client/src/components/citizen/weapons/RegisterWeaponModal.tsx

:tada: feat: safely generate VIN/Serial numbers

---

packages/client/locales/de_DE/common.json
packages/client/locales/fr_FRA/common.json

:globe_with_meridians: Latest additions to FRA and DEU

---

packages/api/src/controllers/leo/incidents/IncidentController.ts
packages/api/src/controllers/leo/my-officers/MyOfficersController.ts
packages/api/tests/smallest-int-in-array.test.ts
packages/client/src/pages/officer/incidents.tsx
packages/types/src/api.ts

:hammer: chore: implement asyncTable for incidents

---

packages/api/prisma/migrations/20220817064415_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts
packages/api/src/controllers/dispatch/DispatchController.ts
packages/api/src/controllers/ems-fd/EmsFdController.ts
packages/api/src/controllers/leo/LeoController.ts
packages/api/src/lib/ems-fd.ts
packages/api/src/lib/leo/activeOfficer.ts
packages/api/src/lib/leo/utils.ts
packages/api/src/lib/prisma.ts
packages/api/src/migrations/inactivityFilter.ts
packages/client/src/components/admin/manage/cad-settings/GeneralSettingsTab.tsx
packages/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx
packages/schemas/src/admin/index.ts

🎉 feat: separated inacitivity filters

---

packages/api/prisma/migrations/20220828120916_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
packages/api/src/controllers/auth/Auth.ts
packages/api/src/controllers/auth/Discord.ts
packages/api/src/controllers/auth/Steam.ts
packages/api/src/controllers/auth/user/UserController.ts
packages/api/src/lib/auth/getSessionUser.ts
packages/api/src/lib/auth/getUserFromUserAPIToken.ts
packages/api/src/lib/auth/setUserTokenCookies.ts
packages/api/src/lib/auth/validateUser.ts
packages/api/src/middlewares/ActiveDeputy.ts
packages/api/src/middlewares/ActiveOfficer.ts
packages/api/src/middlewares/IsAuth.ts
packages/api/src/middlewares/auth/getUser.ts
packages/api/src/utils/jwt.ts
packages/client/src/components/auth/login/LoginForm.tsx
packages/client/src/lib/fetch.ts
packages/client/src/pages/auth/login.tsx
packages/client/src/pages/auth/register.tsx
packages/config/src/index.ts
turbo.json

:rocket: Refresh tokens

---

packages/api/src/controllers/auth/Discord.ts
packages/api/src/controllers/auth/Steam.ts

add await on setUserTokenCookies for Steam and Discord

---

packages/api/src/controllers/admin/manage/AdminManageUnitsController.ts
packages/api/src/controllers/ems-fd/EmsFdController.ts
packages/api/src/controllers/leo/my-officers/MyOfficersController.ts
packages/client/src/components/admin/manage/units/tabs/manage-unit-tab/UnitLogsTab.tsx
packages/client/src/components/leo/logs/OfficerLogsTable.tsx
packages/client/src/hooks/shared/table/useAsyncTable.ts
packages/client/src/pages/ems-fd/my-deputy-logs.tsx
packages/client/src/pages/officer/my-officer-logs.tsx
packages/types/src/api/ems-fd.ts
packages/types/src/api/leo.ts

:tada: feat: add async-table for unit logs

---

packages/api/prisma/migrations/20220903062552_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/record/RecordsController.ts
packages/api/src/lib/prisma.ts
packages/api/src/migrations/permissions/setManageWarrantsPermissions.ts
packages/client/src/components/leo/active-warrants/ActiveWarrants.tsx
packages/client/src/components/leo/modals/NameSearchModal/tabs/WarrantsTab.tsx
packages/client/src/components/modal-buttons/ModalButton.tsx
packages/client/src/components/modal-buttons/buttons.ts
packages/permissions/src/defaults/leo.ts
packages/permissions/src/permissions.ts

:tada: feat: add 'Manage Warrants' permission

---

packages/api/prisma/migrations/20220903144859_/migration.sql
packages/api/prisma/migrations/20220904060949_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/dispatch/911-calls/Calls911Controller.ts
packages/schemas/src/dispatch/911-calls.ts

:tada: feat: add location fields for 911-call & incidents (WIP)

---

packages/api/prisma/migrations/20220905180542_/migration.sql
packages/api/prisma/schema.prisma
packages/client/src/components/dispatch/map/calls/RenderActiveCalls.tsx

🎉 feat: minor map improvements

---

packages/client/src/pages/_app.tsx
packages/client/src/styles/fonts.scss
packages/client/src/styles/globals.scss

[Improvement] Move font definitions to separate file #1084

[Improvement] Move font definitions to separate file #1084

---

packages/api/prisma/migrations/20220916160317_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/admin/manage/courthouse/AdminManageWarrantsController.ts
packages/api/src/controllers/record/RecordsController.ts
packages/api/src/migrations/disabledFeatureToCadFeature.ts
packages/client/locales/en/admin.json
packages/client/locales/en/courthouse.json
packages/client/locales/en/leo.json
packages/client/src/components/admin/Sidebar/routes.ts
packages/client/src/components/admin/manage/cad-settings/CADFeaturesTab.tsx
packages/client/src/components/admin/manage/courthouse/PendingWarrantsTab.tsx
packages/client/src/components/leo/modals/CreateWarrantModal.tsx
packages/client/src/components/leo/modals/NameSearchModal/tabs/WarrantsTab.tsx
packages/client/src/components/shared/Status.tsx
packages/client/src/hooks/useFeatureEnabled.ts
packages/client/src/pages/admin/manage/courthouse.tsx
packages/permissions/src/permissions.ts
packages/types/src/api/admin.ts
packages/types/src/enums.ts

:tada: feat: add approval for warrants (optional feature)

---

packages/api/prisma/migrations/20220918075522_/migration.sql
packages/api/prisma/schema.prisma
packages/api/src/controllers/auth/user/UserController.ts
packages/api/src/controllers/leo/search/SearchController.ts
packages/client/next.config.js
packages/client/src/components/account/AppearanceTab.tsx
packages/client/src/components/dispatch/modals/AddressSearchModal.tsx
packages/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
packages/client/src/hooks/realtime/useActiveCalls.tsx
packages/client/src/pages/officer/jail.tsx

🎉 feat: add speech for incoming calls

---

.github/workflows/test-builds-typecheck.yml

:hammer: chore: update ci

---

apps/client/locales/fr-FR/admin.json
apps/client/locales/fr-FR/common.json
apps/client/locales/fr-FR/courthouse.json
apps/client/locales/fr-FR/leo.json

**Summary:** This revision, namely revision 220922a (or rev/220922a) adds missing translation of elements recently added.
> Note: the letter 'a' is used for personal management of revisions. Next revision will be 230922 (DEU Translation Revision).
> 220922b is a structural revision that do not add changes to SnailyCAD.

:globe_with_meridians: FRA Translation Revision

---

apps/api/prisma/migrations/20220929141301_/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/utils/checkForUpdates.ts
apps/client/src/components/leo/citizen-logs/ArrestReportsTab.tsx
apps/client/src/components/leo/citizen-logs/CitizenLogsTab.tsx
apps/client/src/components/leo/modals/NameSearchModal/tabs/RecordsTab.tsx
apps/client/src/pages/officer/jail.tsx

🎉 feat: add case number to records

---

apps/api/prisma/migrations/20221005123120_/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/values/Import.ts
apps/client/src/components/admin/values/penal-codes/ManagePenalCode.tsx
apps/client/src/pages/admin/values/penal-code.tsx
apps/client/src/pages/officer/penal-codes.tsx
packages/schemas/src/admin/values/import.ts
packages/types/src/enums.ts

🎉 feat: add type for penal code

---

apps/api/src/controllers/dispatch/DispatchController.ts
apps/api/src/controllers/leo/LeoController.ts
apps/api/src/lib/calls/assignUnitsToCall.ts
apps/client/src/components/dispatch/ActiveOfficers.tsx
apps/client/src/components/leo/modals/ManageRecord/TableItemForm.tsx
apps/client/src/hooks/realtime/useActiveDispatchers.ts
apps/client/src/hooks/realtime/useActiveOfficers.ts
apps/client/src/pages/dispatch/index.tsx
apps/client/src/pages/dispatch/map.tsx
apps/client/src/pages/ems-fd/index.tsx
apps/client/src/pages/officer/call-history.tsx
apps/client/src/pages/officer/incidents.tsx
apps/client/src/pages/officer/index.tsx
apps/client/tests/utils.test.ts
packages/types/src/api/dispatch.ts
packages/types/src/api/leo.ts

:hammer: chore: load first 25 officers (improve server time)

---

apps/api/package.json
apps/client/package.json
package.json
packages/config/package.json
packages/permissions/package.json
packages/schemas/package.json
packages/types/package.json
packages/ui/package.json
packages/utils/package.json
yarn.lock

chore: bump deps

---

.github/workflows/test-builds-typecheck.yml

:hammer: chore: add windows runnner for CI

---

.dockerignore
Dockerfile
docker-compose.yml
production.docker-compose.yml

:hammer: build: improved docker config

---

apps/api/src/controllers/leo/incidents/IncidentController.ts
apps/client/src/pages/officer/incidents.tsx
apps/client/src/pages/officer/supervisor/exams.tsx
packages/types/src/api.ts

:tada: feat: improved incidents handling

---

apps/api/src/controllers/admin/manage/AdminManageCitizensController.ts
apps/api/src/controllers/admin/manage/AdminManageUnitsController.ts
apps/api/src/controllers/citizen/CitizenController.ts
apps/api/src/controllers/dispatch/911-calls/Calls911Controller.ts
apps/api/src/lib/citizen.ts
apps/api/src/lib/validateSchema.ts
apps/client/src/components/citizen/ManageCitizenForm.tsx

🔨 chore: apply .partial() to some PUT handlers

---

apps/client/src/components/Dropdown.tsx
apps/client/src/components/leo/modals/NameSearchModal/CreateCitizenModal.tsx
apps/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
apps/client/src/components/leo/modals/NameSearchModal/sections/basic-information.tsx
apps/client/src/components/leo/modals/NameSearchModal/sections/footer-actions.tsx
apps/client/src/components/leo/modals/NameSearchModal/sections/footer.tsx
apps/client/src/components/leo/modals/NameSearchModal/sections/licenses-section.tsx
apps/client/src/components/leo/modals/NameSearchModal/tabs/RecordsTab.tsx

🎉 feat: improve name search footer actions

---

apps/api/prisma/migrations/20221122155409_manage_awards_qualifications_permissions/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/AdminController.ts
apps/api/src/controllers/admin/manage/AdminManageUnitsController.ts
apps/api/src/migrations/permissions/setManageAwardsAndQualificationsPermissions.ts
apps/client/src/components/admin/Sidebar/routes.ts
apps/client/src/components/admin/manage/units/QualificationsTable.tsx
apps/client/src/components/admin/manage/units/tabs/all-units-tab/AllUnitsTab.tsx
apps/client/src/components/admin/manage/units/tabs/manage-unit-tab/ManageUnitTab.tsx
apps/client/src/components/nav/Nav.tsx
apps/client/src/pages/admin/manage/units/[id].tsx
apps/client/src/pages/admin/manage/units/index.tsx
packages/permissions/src/defaults/admin.ts
packages/permissions/src/defaults/leo.ts
packages/permissions/src/permissions.ts

🎉 feat: add ManageAwardsAndQualifications permissions

---

apps/client/src/components/dispatch/modals/Manage911Call/Manage911CallForm.tsx
apps/client/src/components/editor/Editor.tsx
apps/client/src/components/editor/Toolbar.tsx
apps/client/src/components/form/inputs/Checkbox.tsx
apps/client/src/pages/business/[id]/[employeeId]/index.tsx

🔨 chore: editor improvements

---

apps/api/src/controllers/admin/manage/ManageUsersController.ts
apps/client/src/components/admin/manage/users/modals/prune-users-modal.tsx
apps/client/src/components/admin/manage/users/tabs/AllUsersTab.tsx
apps/client/src/pages/admin/manage/users/index.tsx
apps/client/src/types/ModalIds.ts
packages/types/src/api/admin.ts

:tada: feat: user pruning

---

apps/api/prisma/migrations/20221214124333_extra_fields_departmentvalue/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/values/Import.ts
packages/schemas/src/admin/values/import.ts

:tada: feat: `extraFields` for department value

---

apps/client/locales/pt-BR/citizen.json
apps/client/locales/pt-BR/courthouse.json

🌐 [UPDATE] Update Portuguese-BR Translations #2

---

apps/api/src/controllers/auth/Discord.ts
apps/api/src/lib/discord/register-metadata.ts
apps/api/src/main.ts

:tada: feat: Support Discord connected roles

---

apps/api/src/controllers/calls/TaxiController.ts
apps/api/src/controllers/calls/TowController.ts
packages/schemas/src/admin/import/citizens.ts
packages/schemas/src/admin/import/vehicles.ts
packages/schemas/src/admin/index.ts
packages/schemas/src/admin/values/import.ts
packages/schemas/src/auth.ts
packages/schemas/src/bleeter.ts
packages/schemas/src/businesses.ts
packages/schemas/src/citizen.ts
packages/schemas/src/court.ts
packages/schemas/src/dispatch/911-calls.ts
packages/schemas/src/dispatch/index.ts
packages/schemas/src/ems-fd.ts
packages/schemas/src/leo.ts
packages/schemas/src/records.ts
packages/schemas/src/tow.ts
packages/schemas/src/truck-log.ts

:hammer: chore: refactor schemas

---

apps/client/locales/pt-BR/calls.json
apps/client/locales/pt-BR/webhooks.json

🌐 [UPDATE] Update Portuguese-BR Translations

---

apps/api/prisma/migrations/20221224074854_vehicle_records/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/manage/citizens/records-logs-controller.ts
apps/api/src/controllers/leo/search/SearchController.ts
apps/api/src/lib/records/upsert-record.ts
apps/api/src/utils/get-translator.ts
apps/client/src/components/leo/modals/manage-record/manage-record-modal.tsx
apps/client/src/components/leo/modals/manage-record/tabs/vehicle-tab/vehicle-tab.tsx
packages/schemas/src/records.ts
packages/types/src/api/admin.ts
packages/types/src/index.ts
packages/ui/src/components/fields/async-list-search-field.tsx

🎉 feat: option to define vehicle to records

---

apps/api/prisma/migrations/20221231124604_case_number_template/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
apps/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx
apps/client/src/components/leo/modals/NameSearchModal/tabs/records-tab.tsx
apps/client/src/components/leo/records-case-number-column.tsx
apps/client/src/hooks/use-format-case-number.ts
apps/client/src/pages/officer/jail.tsx
apps/client/src/pages/officer/supervisor/citizen-logs/[citizenId].tsx
apps/client/src/styles/globals.scss
packages/schemas/src/admin/index.ts
packages/utils/package.json
packages/utils/src/callsign.ts
packages/utils/src/case-number.ts
packages/utils/src/utils/prefix-number.ts
packages/utils/src/utils/replace-template-variables.ts
packages/utils/tests/case-number.test.ts

:tada: feat: case number template

---

apps/api/prisma/migrations/20230105184737_extra_fields_divisionvalue/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/values/Import.ts
packages/schemas/src/admin/values/import.ts

feat: support extra fields for division value

---

apps/api/src/controllers/admin/manage/AdminManageBusinessesController.ts
apps/api/src/controllers/admin/values/Import.ts
apps/api/src/controllers/business/EmployeeController.ts
apps/client/src/components/business/manage/BusinessTab.tsx
apps/client/src/components/business/manage/EmployeesTab.tsx
apps/client/src/components/business/manage/ManageEmployeeModal.tsx
apps/client/src/pages/admin/manage/businesses/[id].tsx
apps/client/src/pages/admin/manage/businesses/index.tsx
packages/types/src/api/admin.ts

🎉 feat: Business management (admin)

---

apps/api/src/controllers/dispatch/dispatch-controller.ts
apps/api/src/controllers/dispatch/status-controller.ts
apps/api/src/controllers/leo/incidents/IncidentController.ts
apps/api/src/lib/incidents/get-next-incident-id.ts
apps/api/src/lib/incidents/handle-involved-units.ts
apps/api/src/lib/leo/handleStartEndOfficerLog.ts

:tada: feat: Incident Stacking

---

apps/api/package.json
apps/api/src/controllers/dispatch/911-calls/Calls911Controller.ts
apps/api/src/controllers/dispatch/bolo-controller.ts
apps/api/src/controllers/dispatch/dispatch-controller.ts
apps/api/src/controllers/ems-fd/ems-fd-controller.ts
apps/api/src/controllers/leo/LeoController.ts
apps/api/src/controllers/record/records-controller.ts
apps/api/src/lib/calls/handle-end-call.ts
apps/api/src/lib/leo/setInactiveUnitsOffDuty.ts
apps/api/src/middlewares/active-deputy.ts
apps/api/src/middlewares/active-officer.ts
apps/api/src/middlewares/handle-inactivity.ts
apps/api/src/middlewares/is-enabled.ts
apps/api/src/middlewares/use-permissions.ts
apps/api/src/middlewares/valid-path.ts
apps/api/src/services/socket-service.ts

chore: move inactivity to different process

---

apps/client/locales/fr-FR/admin.json
apps/client/locales/fr-FR/citizen.json
apps/client/locales/fr-FR/leo.json
apps/client/locales/fr-FR/values.json

> French Translation - Revision 001_1534 of 21 Jan. 2023

🌐 Add missing `fr-FR` translations

---

apps/api/src/lib/ems-fd.ts
apps/client/src/components/dispatch/map/units/ActiveMapUnits.tsx
apps/client/src/components/dispatch/map/units/PlayerMarker.tsx
apps/client/src/components/dispatch/map/units/RenderMapPlayers.tsx
apps/client/src/hooks/realtime/use-map-players.tsx
apps/client/src/hooks/realtime/useActiveOfficers.ts
apps/client/src/types/Map.ts

:bug: fix(live-map): correctly check for identifiers & users

---

apps/client/src/components/Dropdown.tsx
apps/client/src/components/active-bolos/active-bolos.tsx
apps/client/src/components/dispatch/active-calls/active-calls.tsx
apps/client/src/components/dispatch/active-deputies.tsx
apps/client/src/components/dispatch/active-incidents.tsx
apps/client/src/components/dispatch/active-officers.tsx
apps/client/src/components/leo/active-warrants/ActiveWarrants.tsx
apps/client/src/components/shared/Table/Table.tsx
apps/client/src/components/shared/Table/TableHeader.tsx
apps/client/src/hooks/shared/table/use-table-state.ts

- Allow users to define hidden table columns. Currently not support for every table

feat: hidable table columns

---

apps/client/src/components/ems-fd/modals/SearchMedicalRecords.tsx
apps/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
apps/client/src/components/leo/modals/NameSearchModal/speech-alert.tsx

feat: start with speech for name-search

---

apps/api/src/controllers/admin/manage/units/department-time-logs-controller.ts
apps/client/src/components/admin/manage/units/tabs/department-time-logs/department-time-logs-table.tsx
packages/ui/src/components/fields/date-picker-field.tsx

feat(unit-hours): able to select date range

---

apps/api/src/controllers/admin/manage/AdminManageBusinessesController.ts
apps/api/src/controllers/admin/manage/AdminManageCustomFieldsController.ts
apps/api/src/controllers/admin/manage/AdminManageCustomRolesController.ts
apps/api/src/controllers/admin/manage/cad-settings/CADImagesController.ts
apps/api/src/controllers/admin/manage/cad-settings/discord/DiscordSettingsController.ts
apps/api/src/controllers/admin/manage/cad-settings/discord/DiscordWebhooksController.ts
apps/api/src/controllers/admin/manage/courthouse/AdminManageExpungementRequests.ts
apps/api/src/controllers/admin/manage/manage-users-controller.ts
apps/api/src/controllers/admin/manage/units/manage-units-controller.ts
apps/api/src/lib/leo/findUnit.ts
packages/audit-logger/src/types/action-types.ts
packages/audit-logger/src/types/actions.ts

:rocket: feat: add more audit log actions

---

.deepsource.toml
.eslintrc
apps/api/src/controllers/admin/manage/units/department-time-logs-controller.ts
apps/api/src/controllers/admin/manage/units/manage-units-controller.ts
apps/api/src/lib/leo/utils.ts
apps/api/src/utils/zod-error-map.ts
apps/client/src/components/admin/manage/users/modals/manage-permissions-modal.tsx
apps/client/src/components/editor/elements/element.tsx
apps/client/src/hooks/realtime/use-map-players.tsx
apps/client/src/hooks/useGenerateCallsign.ts
apps/client/src/lib/editor/withShortcuts.ts
apps/client/src/lib/server/getAvailableSounds.server.ts
apps/client/src/lib/validation/zod-error-map.ts
package.json
packages/config/src/index.ts
packages/types/src/enums.ts
yarn.lock

- Upgrade linting dependencies 
- Upgrade prettier

chore: upgrade prettier

---

apps/api/package.json
apps/api/src/controllers/auth/user/user-controller.ts
apps/api/src/lib/auth/setUserTokenCookies.ts
apps/api/src/utils/set-cookie.ts
yarn.lock

- Improved checking if `DOMAIN` is properly defined.

chore: experiment with domain issues

---

apps/api/prisma/migrations/20230209165735_multi_discord_guild_support/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/manage/cad-settings/discord/DiscordSettingsController.ts
apps/api/src/controllers/admin/manage/cad-settings/discord/DiscordWebhooksController.ts
apps/api/src/lib/discord/auth.ts
apps/api/src/lib/discord/utils.ts

feat: support multiple Discord Guilds

---

package.json
yarn.lock

Upgrades Turbo to the latest version

chore: upgrade Turbo

---

apps/api/src/controllers/bleeter/BleeterController.ts
apps/client/src/components/bleeter/ManageBleetModal.tsx
apps/client/src/components/bleeter/manage-bleet-modal.tsx
apps/client/src/components/editor/editor.tsx
apps/client/src/components/shared/FullDate.tsx
apps/client/src/pages/bleeter/[id].tsx
apps/client/src/pages/bleeter/index.tsx
packages/types/src/api.ts

:sparkles: feat: Bleeter feed

---

apps/client/locales/en/calls.json
apps/client/src/components/dispatch/modals/Manage911Call/add-unit-to-call-modal.tsx

feat: able to assign multiple units to a call at the same time

---

apps/client/src/components/citizen/vehicles/vehicles-card.tsx
apps/client/src/components/dispatch/modals/Manage911Call/AssignedUnitsTable.tsx

🎉 feat: able to change unit status in call modal

---

apps/api/prisma/migrations/20230306153731_dispatch_department_filter/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/dispatch/dispatch-controller.ts
apps/api/src/controllers/ems-fd/ems-fd-controller.ts
apps/api/src/controllers/leo/LeoController.ts
apps/client/locales/en/leo.json
apps/client/src/components/dispatch/ModalButtons.tsx
apps/client/src/components/dispatch/modals/select-department-modal.tsx
apps/client/src/components/modal-buttons/buttons.ts
apps/client/src/pages/dispatch/index.tsx
apps/client/src/state/dispatch/active-dispatcher-state.ts
apps/client/src/types/ModalIds.ts
packages/types/src/api/dispatch.ts
packages/types/src/index.ts

feat: able to select active department

---

apps/api/src/controllers/nav-controller.ts
apps/api/src/middlewares/use-permissions.ts
apps/client/src/components/admin/Sidebar.tsx
apps/client/src/components/admin/manage/courthouse/expungement-requests-tab.tsx
apps/client/src/components/admin/manage/courthouse/name-change-requests-tab.tsx
apps/client/src/components/admin/manage/courthouse/pending-warrants-tab.tsx
apps/client/src/components/nav/Nav.tsx
apps/client/src/components/nav/dropdowns/admin-link.tsx
apps/client/src/hooks/use-invalidate-query.ts

feat: add notifications for /admin

---

apps/api/prisma/migrations/20230330175639_employee_permissions/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/manage/manage-businesses-controller.ts
apps/api/src/controllers/business/EmployeeController.ts
apps/api/src/controllers/business/business-roles-controller.ts
apps/api/src/controllers/citizen/vehicles-controller.ts
apps/client/locales/en/business.json
apps/client/src/components/business/manage/tabs/employees-tab/manage-employee-modal.tsx
apps/client/src/pages/business/[id]/[employeeId]/index.tsx
apps/client/src/pages/business/[id]/[employeeId]/manage.tsx
apps/client/src/pages/business/index.tsx
packages/schemas/src/businesses.ts

feat: add more permissions for business employees

---

apps/api/src/controllers/dispatch/combined-units-controller.ts
apps/api/src/lib/leo/activeOfficer.ts
apps/client/src/components/dispatch/active-deputies.tsx
apps/client/src/components/dispatch/active-officers.tsx
apps/client/src/components/dispatch/active-units/merge-unit-modal.tsx
apps/client/src/hooks/leo/use-get-user-officers.ts
packages/schemas/src/leo.ts

feat: able to select patrol vehicle for combined units

---

apps/api/src/controllers/ems-fd/ems-fd-controller.ts
apps/client/src/components/ems-fd/modals/SearchMedicalRecords.tsx
apps/client/src/components/leo/modals/NameSearchModal/sections/footer-actions.tsx
packages/permissions/src/defaults/leo.ts
packages/permissions/src/permissions.ts

feat: `DeclareCitizenDead` permissions (#1605

---

apps/client/src/components/account/appearance-tab.tsx
apps/client/src/components/admin/manage/cad-settings/default-permissions-tab.tsx
apps/client/src/components/admin/manage/units/tabs/manage-unit-tab/manage-unit-tab.tsx
apps/client/src/components/admin/manage/users/modals/manage-permissions-modal.tsx
apps/client/src/components/admin/values/ManageValueModal.tsx
apps/client/src/components/admin/values/manage-modal/DepartmentFields.tsx
apps/client/src/components/admin/values/manage-modal/LicenseFields.tsx
apps/client/src/components/business/CreateBusinessModal.tsx
apps/client/src/components/business/manage/tabs/employees-tab/manage-employee-modal.tsx
apps/client/src/components/citizen/licenses/ManageLicensesFormFields.tsx
apps/client/src/components/citizen/vehicles/modals/register-vehicle-modal.tsx
apps/client/src/components/citizen/weapons/register-weapon-modal.tsx
apps/client/src/components/dispatch/modals/Manage911Call/add-unit-to-call-modal.tsx
apps/client/src/components/dispatch/modals/tones-modal.tsx
apps/client/src/components/leo/incidents/manage-incident-modal.tsx
apps/client/src/components/leo/modals/manage-record/manage-record-modal.tsx
apps/client/src/components/leo/modals/manage-record/tabs/seized-items-tab/manage-seized-items-modal.tsx
apps/client/src/pages/business/[id]/[employeeId]/manage.tsx
packages/ui/package.json
packages/ui/src/components/fields/switch-field.tsx
packages/ui/src/components/index.tsx
yarn.lock

Use React Aria for a new `SwitchField`

feat: updated switch field

---

apps/client/locales/en/values.json

uppercase first letter of words

---

apps/api/prisma/migrations/20230513074203_doctor_visits/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/ems-fd/ems-fd-controller.ts
apps/api/src/controllers/leo/search/SearchController.ts
apps/client/locales/en/ems-fd.json
apps/client/next-env.d.ts
apps/client/src/components/ems-fd/ModalButtons.tsx
apps/client/src/components/ems-fd/modals/doctor-visits/create-doctor-visit-modal.tsx
apps/client/src/components/ems-fd/modals/search-medical-records/search-medical-records-modal.tsx
apps/client/src/components/ems-fd/modals/search-medical-records/tabs/doctor-visits-tab.tsx
apps/client/src/components/ems-fd/modals/search-medical-records/tabs/medical-records-tab.tsx
apps/client/src/pages/ems-fd/index.tsx
apps/client/src/types/ModalIds.ts
apps/client/tsconfig.json
packages/schemas/src/ems-fd.ts
packages/types/src/api/ems-fd.ts
packages/types/src/api/search.ts
packages/types/src/index.ts

feat: doctor visits

---

apps/api/prisma/migrations/20230526154910_extra_fields_cad_feature/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
apps/api/src/middlewares/is-auth.ts
apps/api/src/middlewares/is-enabled.ts
apps/client/src/components/admin/manage/cad-settings/CADFeaturesTab.tsx
apps/client/src/components/form/SettingsFormField.tsx
apps/client/src/components/leo/exams/ManageExamModal.tsx
apps/client/src/hooks/useFeatureEnabled.ts
packages/schemas/src/admin/index.ts
packages/types/src/index.ts

feat: toggable license exams

---

apps/api/prisma/migrations/20230527085026_license_points/migration.sql
apps/api/prisma/migrations/20230527094212_license_points/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
apps/api/src/controllers/citizen/CitizenController.ts
apps/api/src/controllers/leo/search/SearchActionsController.ts
apps/client/locales/en/citizen.json
apps/client/locales/en/leo.json
apps/client/src/components/admin/manage/cad-settings/MiscFeatures.tsx
apps/client/src/components/admin/manage/cad-settings/misc-features/max-license-points.tsx
apps/client/src/components/citizen/licenses/ManageLicensesFormFields.tsx
apps/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
apps/client/src/components/leo/modals/NameSearchModal/sections/license-points/license-points.tsx
apps/client/src/components/leo/modals/NameSearchModal/sections/license-points/manage-license-points-modal.tsx
apps/client/src/components/leo/modals/NameSearchModal/sections/licenses-section.tsx
apps/client/src/types/ModalIds.ts
packages/schemas/src/admin/index.ts
packages/schemas/src/leo.ts
packages/types/src/api/search.ts
packages/types/src/index.ts

feat: license points

---

apps/client/src/components/dispatch/map/units/active-map-units.tsx
apps/client/src/hooks/realtime/useActiveDeputies.ts
apps/client/src/hooks/realtime/useActiveOfficers.ts
apps/client/src/lib/map/create-map-units-from-active-units.ts.ts

> **Warning**
> Must be tested first!

fix: properly sync all unit types on live map

---

apps/api/prisma/migrations/20230615113018_custom_template_department_value/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/values/import-values-controller.ts
apps/client/locales/en/values.json
apps/client/src/components/admin/manage/cad-settings/misc-features/template-section.tsx
apps/client/src/components/admin/values/ManageValueModal.tsx
apps/client/src/components/admin/values/manage-modal/department-fields.tsx
apps/client/src/lib/admin/values/values.tsx
packages/schemas/src/admin/values/import.ts
packages/utils/src/callsign.ts

feat: custom template for department value

---

apps/api/prisma/migrations/20230615115745_user_defined_callsign_units/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/dispatch/status-controller.ts
apps/api/src/controllers/ems-fd/incidents/ems-fd-incidents-controller.ts
apps/client/locales/en/cad-settings.json
apps/client/locales/en/leo.json
apps/client/src/components/ems-fd/modals/select-deputy-modal.tsx
apps/client/src/components/leo/CallsignPreview.tsx
apps/client/src/components/leo/modals/select-officer-modal.tsx
apps/client/src/hooks/use-permissions-modal.tsx
apps/client/src/hooks/useGenerateCallsign.ts
packages/permissions/src/permissions.ts
packages/schemas/src/ems-fd.ts
packages/schemas/src/leo.ts
packages/utils/src/callsign.ts

feat: user defined callsign

---

apps/api/src/middlewares/is-enabled.ts
apps/client/locales/en/cad-settings.json
apps/client/src/components/admin/manage/cad-settings/cad-features-tab.tsx
apps/client/src/hooks/useFeatureEnabled.ts
apps/client/src/pages/admin/manage/courthouse.tsx
apps/client/src/pages/courthouse.tsx
packages/types/src/enums.ts
packages/types/src/lib/cad-feature.ts

feat: ability to select courthouse types

---

apps/api/prisma/migrations/20230706120138_signal_100_repeat_settings/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
apps/client/locales/en/cad-settings.json
apps/client/src/components/admin/manage/cad-settings/misc-settings-tab.tsx
apps/client/src/hooks/shared/useSignal100.tsx
packages/schemas/src/admin/index.ts

feat: signal 100 repeat

---

apps/client/locales/ru/cad-settings.json

🌐 chore: Adding missing Russian locales
🔧 Changes: 🔧 
Added to RU translation:
- Locales for `cad-settings`
✅  `.json` files are formatted: `yarn format`
✅  Translations are correct
In this PR I've added new locales that were introduced in the recent 1.64.0 update
Please review and merge this pull request at your earliest convenience.
Thank you!

🌐  chore: Adding missing Russian locales

---

apps/api/prisma/migrations/20230716142458_medical_record_desc_data/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/citizen/MedicalRecordController.ts
apps/api/src/controllers/ems-fd/ems-fd-controller.ts
apps/client/src/components/citizen/medical-records/manage-medical-records-modal.tsx
apps/client/src/components/citizen/medical-records/medical-records.tsx
apps/client/src/components/ems-fd/modals/CreateMedicalRecord.tsx
apps/client/src/components/ems-fd/modals/search-medical-records/tabs/medical-records-tab.tsx
apps/client/src/components/leo/modals/VehicleSearchModal.tsx
packages/schemas/src/citizen.ts

feat(medical-records): allow rich text

---

apps/client/src/components/citizen/medical-records/manage-medical-records-modal.tsx
apps/client/src/components/editor/editor.tsx
apps/client/src/components/ems-fd/modals/CreateMedicalRecord.tsx

- Removed outline of overlaying textfield above slate and aligned it
- Let the modal windows of medical records to be auto-width

chore(ui): Editor textfield visual fixes

---

apps/api/prisma/migrations/20230718154053_weapon_flags/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/values/import-values-controller.ts
apps/api/src/controllers/leo/search/SearchActionsController.ts
apps/api/src/controllers/leo/search/SearchController.ts
apps/api/src/lib/values/utils.ts
apps/api/src/middlewares/valid-path.ts
apps/api/tests/value-utils.test.ts
apps/client/locales/en/leo.json
apps/client/locales/en/values.json
apps/client/src/components/admin/Sidebar/routes.ts
apps/client/src/components/leo/modals/weapon-search-modal.tsx
apps/client/src/components/leo/modals/weapon-search/manage-weapon-flags-modal.tsx
apps/client/src/context/ValuesContext.tsx
apps/client/src/lib/admin/values/isValueInUse.ts
apps/client/src/pages/dispatch/index.tsx
apps/client/src/pages/officer/index.tsx
apps/client/src/types/modal-ids.ts
apps/client/tests/values.test.ts
packages/permissions/src/permissions.ts
packages/types/src/api/search.ts
packages/types/src/enums.ts
packages/types/src/index.ts

feat: ability to add weapon flags

---

apps/api/prisma/migrations/20230722075127_records_rich_text/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/lib/leo/records/upsert-record.ts
apps/client/src/components/dispatch/active-calls/CallDescription.tsx
apps/client/src/components/leo/modals/NameSearchModal/NameSearchModal.tsx
apps/client/src/components/leo/modals/NameSearchModal/tabs/records-tab.tsx
apps/client/src/components/leo/modals/NameSearchModal/tabs/tabs-container.tsx
apps/client/src/components/leo/modals/VehicleSearchModal.tsx
apps/client/src/components/leo/modals/manage-record/manage-record-modal.tsx
packages/schemas/src/records.ts
packages/ui/src/components/hover-card.tsx

feat: records rich text notes

---

apps/api/prisma/migrations/20230806071701_vehicle_model_images/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/values/values-controller.ts
apps/api/src/controllers/citizen/vehicles-controller.ts
apps/client/locales/en/citizen.json
apps/client/src/components/admin/values/ManageValueModal.tsx
apps/client/src/components/admin/values/manage-modal/vehicle-fields.tsx
apps/client/src/components/citizen/vehicles/modals/register-vehicle-modal.tsx
apps/client/src/components/citizen/vehicles/vehicles-card.tsx
apps/client/src/components/leo/modals/VehicleSearch/tabs/ResultsTab.tsx
apps/client/src/components/leo/modals/VehicleSearchModal.tsx
apps/client/src/lib/admin/values/values.tsx

feat: vehicle model images

---

apps/client/locales/en/leo.json
apps/client/src/components/dispatch/map/calls/call-item.tsx
apps/client/src/components/dispatch/map/calls/render-active-map-calls.tsx
apps/client/src/components/dispatch/map/map-actions.tsx
apps/client/src/components/dispatch/map/map.tsx
apps/client/src/components/dispatch/map/render-map-blips.tsx
apps/client/src/components/dispatch/map/smart-signs/render-map-smart-signs.tsx
apps/client/src/components/dispatch/map/smart-signs/smart-sign-marker.tsx
apps/client/src/components/dispatch/map/smart-signs/use-smart-signs.tsx
apps/client/src/components/dispatch/map/units/active-map-units.tsx
apps/client/src/components/dispatch/map/units/player-marker.tsx
apps/client/src/components/dispatch/map/units/render-map-players.tsx
apps/client/src/hooks/realtime/use-map-players.tsx
apps/client/src/hooks/realtime/useActiveDeputies.ts
apps/client/src/hooks/realtime/useActiveOfficers.ts
apps/client/src/lib/map/blips.ts
apps/client/src/lib/map/utils.ts
apps/client/src/state/mapState.ts
apps/client/src/types/map.ts
packages/permissions/src/permissions.ts

feat: London Studios SmartSigne integration 

---

apps/api/prisma/migrations/20230821091842_comments_on_courthouse_requests/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/court/ExpungementRequestsController.ts
apps/api/src/controllers/court/NameChangeRequestController.ts
apps/client/src/components/admin/manage/courthouse/expungement-requests-tab.tsx
apps/client/src/components/admin/manage/courthouse/name-change-requests-tab.tsx
apps/client/src/components/courthouse/expungement-requests/expungement-requests-tab.tsx
apps/client/src/components/courthouse/expungement-requests/request-expungement-modal.tsx
apps/client/src/components/courthouse/name-change/name-change-requests-tab.tsx
apps/client/src/components/courthouse/name-change/request-name-change-modal.tsx
packages/schemas/src/court.ts

feat: able to specify a description on name change/expungement requests

---

apps/api/src/controllers/admin/manage/cad-settings/CadSettings.ts
apps/api/src/controllers/admin/manage/manage-users-controller.ts
apps/api/src/controllers/admin/manage/units/manage-units-controller.ts
apps/client/locales/en/cad-settings.json
apps/client/src/components/admin/manage/cad-settings/webhooks/raw-webhooks-tab.tsx
tsconfig.base.json

feat(raw-webhooks): user/department whitelist status change

---

apps/api/prisma/migrations/20230907142434_impounded_vehicle_description/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/leo/search/SearchActionsController.ts
apps/api/src/lib/discord/webhooks.ts
apps/client/src/components/leo/modals/VehicleSearch/impound-vehicle-modal.tsx
apps/client/src/components/leo/modals/VehicleSearchModal.tsx
apps/client/src/pages/officer/impound-lot.tsx
packages/schemas/src/leo.ts

feat(impound-lot): improvements & fixes

---

apps/api/src/controllers/nav-controller.ts
apps/api/src/lib/discord/webhooks.ts
apps/client/src/components/leo/citizen-logs/arrest-reports-tab.tsx
apps/client/src/components/leo/modals/manage-record/manage-record-modal.tsx
apps/client/src/components/leo/modals/manage-record/tabs/connections-tab/connections-tab.tsx
apps/client/src/components/shared/nav/dropdowns/OfficerDropdown.tsx
packages/ui/src/components/stories/fields/async-list-field.stories.tsx

feat: citizen logs notifications

---

apps/api/prisma/migrations/20230908142856_department_links/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/values/import-values-controller.ts
apps/api/src/controllers/admin/values/values-controller.ts
apps/api/src/utils/leo/includes.ts
apps/client/locales/en/leo.json
apps/client/src/components/admin/values/ManageValueModal.tsx
apps/client/src/components/admin/values/manage-modal/department-fields.tsx
apps/client/src/components/admin/values/manage-modal/department-links-section.tsx
apps/client/src/components/ems-fd/ModalButtons.tsx
apps/client/src/components/leo/ModalButtons.tsx
apps/client/src/components/leo/modals/department-info-modal.tsx
apps/client/src/components/modal-buttons/buttons.ts
apps/client/src/pages/ems-fd/index.tsx
apps/client/src/pages/officer/index.tsx
apps/client/src/types/modal-ids.ts
packages/schemas/src/admin/values/import.ts
packages/types/src/index.ts

feat: able to add department links

---

apps/api/prisma/migrations/20230912142000_license_exams_fix/migration.sql
apps/api/prisma/schema.prisma
apps/client/package.json
pnpm-lock.yaml

refactor: license exam model

---

apps/api/prisma/migrations/20230925150249_extended_ems_fd_incidents/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/ems-fd/incidents/ems-fd-incidents-controller.ts
apps/client/locales/en/leo.json
apps/client/src/components/leo/incidents/manage-incident-modal.tsx
packages/schemas/src/leo.ts

feat: extended EMS/FD incidents

---

apps/api/src/controllers/admin/manage/citizens/records-logs-controller.ts
apps/api/src/controllers/leo/LeoController.ts
apps/client/locales/en/common.json
apps/client/locales/en/leo.json
apps/client/src/components/shared/nav/dropdowns/officer-dropdown.tsx
apps/client/src/pages/officer/my-record-reports.tsx
packages/types/src/api/leo.ts

feat(leo): my record report

---

apps/client/locales/en-gb/leo.json
apps/client/locales/en-gb/values.json

Updating translations added in d12276ca0a5b97bd9a228406aa1e653f82b1d306

:hammer: chore: update translations (en-gb)

---

apps/api/prisma/migrations/20231006080836_other_license_category/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/lib/citizen/licenses/update-citizen-license-categories.ts
apps/client/locales/en/citizen.json
apps/client/src/components/citizen/licenses/ManageLicensesFormFields.tsx
apps/client/src/components/citizen/licenses/licenses-card.tsx
apps/client/src/components/citizen/licenses/manage-licenses-modal.tsx
apps/client/src/components/dispatch/active-units/deputies/active-deputies.tsx
apps/client/src/components/dispatch/active-units/deputies/deputy-column.tsx
apps/client/src/components/dispatch/active-units/officers/active-officers.tsx
apps/client/src/components/dispatch/active-units/officers/columns/officer-column.tsx
packages/schemas/src/admin/values/import.ts
packages/schemas/src/citizen.ts
packages/types/src/enums.ts

feat: Other license categories

---

apps/client/locales/fr-FR/citizen.json

chores: Update french translation

---

apps/api/src/controllers/admin/manage/citizens/records-logs-controller.ts
apps/client/src/components/leo/citizen-logs/pending-citizen-logs-tab.tsx
apps/client/src/components/leo/modals/manage-record/manage-record-modal.tsx
apps/client/src/hooks/shared/table/use-async-table.ts
apps/client/src/pages/officer/supervisor/citizen-logs/index.tsx
packages/types/src/api/admin.ts

fix: pending citizen logs

---

apps/api/prisma/migrations/20231021140807_deletable_penal_codes/migration.sql
apps/api/prisma/schema.prisma
apps/client/locales/en/leo.json
apps/client/src/components/courthouse/expungement-requests/request-expungement-modal.tsx
apps/client/src/components/form/select/MultiValueContainerPenalCode.tsx
apps/client/src/components/leo/ViolationsColumn.tsx
apps/client/src/components/leo/modals/manage-record/manage-record-modal.tsx
apps/client/src/components/leo/modals/manage-record/penal-codes-table.tsx
apps/client/src/components/leo/modals/manage-record/table-item-form.tsx
packages/types/src/api/admin.ts
packages/types/src/index.ts

feat: deleteable penal codes

---

apps/api/prisma/migrations/20231023170026_disposition_code_call/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/values/import-values-controller.ts
apps/client/locales/en/calls.json
apps/client/locales/en/values.json
apps/client/src/components/admin/values/ManageValueModal.tsx
apps/client/src/components/dispatch/active-calls/modals/manage-911-call-form.tsx
apps/client/src/components/form/inputs/value-select-field.tsx
apps/client/src/lib/admin/values/values.tsx
packages/schemas/src/admin/values/import.ts

feat: call 911 disposition code

---

apps/client/locales/ru/cad-settings.json
apps/client/locales/ru/calls.json
apps/client/locales/ru/leo.json
apps/client/locales/ru/values.json
apps/client/locales/ru/webhooks.json

💬 Update 'ru' locale

---

.github/workflows/chromatic.yml
packages/ui/package.json

chore: re-enable Chromatic

---

apps/api/prisma/migrations/20231122144146_use_updated_at_units/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/admin/manage/units/manage-units-controller.ts
apps/api/src/controllers/citizen/CitizenController.ts
apps/api/src/controllers/dispatch/dispatch-controller.ts
apps/api/src/controllers/dispatch/status-controller.ts
apps/api/src/controllers/ems-fd/ems-fd-controller.ts
apps/api/src/controllers/leo/LeoController.ts
apps/api/src/lib/get-active-ems-fd-deputy.ts
apps/api/src/lib/leo/activeOfficer.ts
apps/api/src/lib/leo/setInactiveUnitsOffDuty.ts
apps/api/src/lib/leo/utils.ts
apps/api/src/middlewares/handle-inactivity.ts
apps/api/src/services/socket-service.ts
apps/client/src/components/admin/manage/cad-settings/misc-features/inactivity-timeout-tab.tsx
apps/client/src/components/admin/manage/units/tabs/all-units-tab/prune-units-modal.tsx

fix: unit inactivity timeouts

---

apps/api/src/controllers/ems-fd/ems-fd-controller.ts
apps/api/src/controllers/leo/LeoController.ts
packages/schemas/src/leo.ts

feat: able to force panic button

---

apps/api/prisma/migrations/20231202095501_description_emergency_value/migration.sql
apps/api/prisma/schema.prisma
apps/client/src/components/admin/values/ManageValueModal.tsx
apps/client/src/components/admin/values/manage-modal/emergency-vehicle-fields.tsx
apps/client/src/components/dispatch/active-units/deputies/active-deputies.tsx
apps/client/src/components/dispatch/active-units/officers/active-officers.tsx

feat: description emergency vehicle value

---

apps/api/prisma/migrations/20231223155548_draft_records/migration.sql
apps/api/prisma/schema.prisma
apps/api/src/controllers/leo/search/SearchController.ts
apps/api/src/controllers/record/records-controller.ts
apps/api/src/lib/leo/records/upsert-record.ts
apps/client/locales/en/leo.json
apps/client/src/components/leo/modals/manage-record/manage-record-modal.tsx
apps/client/src/components/leo/modals/manage-record/tabs/drafts-tab/drafts-tab.tsx
packages/schemas/src/records.ts
packages/types/src/enums.ts
packages/types/src/index.ts
packages/ui/src/components/alert/alert.tsx
packages/ui/src/components/tab-list.tsx

feat: draft records

---

apps/api/prisma/migrations/20240106074701_warrant_case_number/migration.sql
apps/api/prisma/schema.prisma
apps/client/src/components/admin/manage/courthouse/pending-warrants-tab.tsx
apps/client/src/components/leo/modals/NameSearchModal/tabs/warrants-tab.tsx
apps/client/src/components/leo/records-case-number-column.tsx
apps/client/src/hooks/use-format-case-number.ts
apps/client/src/pages/officer/my-record-reports.tsx
apps/client/src/pages/officer/supervisor/citizen-logs/[citizenId].tsx
packages/utils/src/case-number.ts

feat: warrant case numbers

---

apps/client/src/components/admin/manage/cad-settings/live-map-tab.tsx
apps/client/src/components/dispatch/map/calls/active-map-calls.tsx
apps/client/src/components/dispatch/map/calls/call-item.tsx
apps/client/src/components/dispatch/map/calls/render-active-map-calls.tsx
apps/client/src/components/dispatch/map/calls/use-marker-change.ts
apps/client/src/components/dispatch/map/map-actions.tsx
apps/client/src/components/dispatch/map/map.tsx
apps/client/src/components/dispatch/map/sidebar/map-sidebar.tsx
apps/client/src/components/dispatch/map/units/active-map-units.tsx
apps/client/src/components/dispatch/map/units/render-map-players.tsx
apps/client/src/hooks/realtime/use-active-dispatchers.ts
apps/client/src/hooks/realtime/use-map-players.tsx
apps/client/src/lib/map/create-map-units-from-active-units.ts.ts
apps/client/src/pages/dispatch/map.tsx
apps/client/src/state/mapState.ts

feat: improved live map UI

---

apps/api/package.json
pnpm-lock.yaml

Update Prisma to the newest version.

---

apps/api/package.json
pnpm-lock.yaml

Reverts SnailyCAD/snaily-cadv4#1906

Revert "Update Prisma to the newest version."

---

apps/api/src/controllers/admin/manage/manage-users-controller.ts

🔨 fix: delete user with pet medical record

---

.github/workflows/cancel.yml
.github/workflows/lint.yml
.github/workflows/test-builds-typecheck.yml
apps/api/src/controllers/record/records-controller.ts
apps/client/next.config.mjs
apps/client/tests/utils.test.ts

Copy of main branch

---

apps/client/src/components/citizen/vehicles/modals/register-vehicle-modal.tsx

Made Trim level Optional 

---

.github/workflows/lint.yml
.github/workflows/test-builds-typecheck.yml

chore: test on Node 20

---

apps/api/src/controllers/admin/manage/manage-users-controller.ts

Added option to return officers and ems deputies related to a User, similar to the logic already in place for Citizens in endpoint ``v1/admin/manage/users/{id}``

feat(user-controller): added option to return user related officers and deputies

---

apps/api/src/controllers/admin/manage/manage-users-controller.ts
apps/api/src/controllers/admin/manage/units/manage-units-controller.ts
apps/api/src/controllers/leo/LeoController.ts
apps/client/locales/en/cad-settings.json
apps/client/src/components/admin/Sidebar/routes.ts
apps/client/src/components/admin/manage/units/tabs/callsigns-tab/manage-unit-callsign-modal.tsx
apps/client/src/pages/admin/manage/units/index.tsx
packages/permissions/src/defaults/admin.ts
packages/permissions/src/permissions.ts
packages/schemas/src/leo.ts

Manage unit rank role
